### ISSUE TITLE
Error when compiling with Java 8

### ISSUE THREAD

**Issue by toix** [charite/jannovar#109]
**Setup:**
Windows 7 and Ubuntu 14.04 LTS
Java: Java SE Development Kit 8 (jdk1.8.0_31)
Maven: 3.2.5

**Steps:**
Install Java
Install Maven
Terminal Command: mvn package -e

**(unwanted) Result:**
log: https://drive.google.com/file/d/0Bzk9C86qSsTgeEk5b2dpemtIQVk/view?usp=sharing

**Comment by holtgrewe** [comment]
This is caused by the HTSJDK from the seqdoop people being built against an old version of cofoja.

I will see what I can do about this (most probably a newer version of HTSJDK has to be uploaded somewhere).

**Comment by holtgrewe** [comment]
The nice people of samtools/HTSJDK have created an official HTSJDK release on Maven central.

#125 should fix this. Please reopen if the problem persists after merging or the next release.
