### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#120]
- [x] describe data source file extension
- [x] describe commands and options in detail
  - [x] jannovar-cli
  - [x] jannovar-filter
- [ ] describe the pedigree module and filters
- [ ] tutorial on coordinate transformation

**Comment by holtgrewe** [comment]
@visze Could you complete the documentation of the filters in the file `manual/ped_filters.rst` for the 1.0 release?

**Comment by visze** [comment]
I should do so...
