### ISSUE TITLE
Clarify insertions at exon/intron borders

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#126]
There are some questions (example is `chr2:g.71062833_71062834insC`):

* consider as intronic consider as exonic?
* could additionally be interpreted as affecting splicing...

**Comment by pnrobinson** [comment]
THese definitely can affect splicing, but we need to consider at what level to evaluate them

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universit�t Berlin
Institut f�r Medizinische Genetik und Humangenetik
Charit� - Universit�tsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________________
Von: Manuel Holtgrewe [notifications@github.com]
Gesendet: Mittwoch, 18. Februar 2015 18:53
An: charite/jannovar
Betreff: [jannovar] Clarify insertions at exon/intron borders (#126)

There are some questions (example is chr2:g.71062833_71062834insC):

 *   consider as intronic consider as exonic?
 *   could additionally be interpreted as affecting splicing...

�

**Comment by holtgrewe** [comment]
Implemented by #164
