### ISSUE TITLE
Add functionality to filter out variants that are incompatible with inheritance

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#135]
Currently, one can only check for compatibility but it would be nice to have functionality to get flags for which variant is compatible.

**Comment by visze** [comment]
inheritance brain fu..

X-Recessive:

* We consider an hemizygous mutations in affected males as disease causing.
* We consider an heterozygous call in an affected male as disease causing => maybe estimated wrong from the caller
* [Singe case] We consider homozygous or two heterozygous mutations in an affected female as disease causing
* [Multiple case] We consider only homozygous mutations in affected females as disease causing. Compound het. will not be checked. Apparently the pedigree will look dominant.

Now the question: How should we handle het. unaffected males, when we have an affected female:

1. loose: Het. mutations in unaffected males are considered as FP calls and are NOT a disqualifying criterion
2.  strict:  A het. mutation in unaffected males IS a disqualifying criterion
3. strict/loose: Het. mutations in unaffected males are considered as FP EXCEPT the father of an affected female is heterozygous. (this is the actual implementation. not really consequent).

**Comment by visze** [comment]
For my last comment please go to issue #95 This issue is something different!

**Comment by holtgrewe** [comment]
Is this done?

**Comment by visze** [comment]
I didn't touch this issue. My two comments belongs to issue #95

**Comment by holtgrewe** [comment]
@visze OK, so I should ignore the "inheritance brain fu.." comment?

**Comment by visze** [comment]
Yes
Am 28.04.2015 13:54 schrieb "Manuel Holtgrewe" <notifications@github.com>:

**Comment by visze** [comment]
Implemented in v0.15
