### ISSUE TITLE
empty annotatons - missing annotation String

### ISSUE THREAD

**Issue by martenj** [charite/jannovar#165]
some variants have incomplete annotations with complete empty string or partly missing string.
e.g.
"&stop_lost" or "&splice_region_variant"

chr3    138495007       .       ATTTGTT AT      179.57  .       AB=0.411765;ABP=4.1599;AC=1;AF=0.5;AN=2;ANN=AT|&stop_lost|HIGH|CEP70|gene10318|transcript|NM_001288964.1|Coding|18/18|c.1743_*4del|p.*581Asnext*25|2073/100045|1743/1743|581/581||;AO=7;CIGAR=1M5D1M;DP=17;DPB=12.7143;DPRA=0;EPP=5.80219;EPPR=4.09604;GTI=0;LEN=5;MEANALT=2;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=41.3474;PAIRED=1;PAIREDR=0.875;PAO=0;PQA=0;PQR=33;PRO=1;QA=261;QR=315;RO=8;RPL=3;RPP=3.32051;RPPR=20.3821;RPR=4;RUN=1;SAF=5;SAP=5.80219;SAR=2;SRF=5;SRP=4.09604;SRR=3;TYPE=del;technology.ILLUMINAHiSeq1500=1        GT:DP:RO:QR:AO:QA:GL    0/1:17:8:315:7:261:-22.797,0,-27.6741
chr16   2771987 .       TCC     TC      181.34  .       AB=0;ABP=0;AC=2;AF=1;AN=2;ANN=TC|&stop_lost|HIGH|TCEB2|gene37874|transcript|NM_007108.3|Coding|4/4|c.359del|p.*120Aspext*10|416/5883|359/360|120/120||;AO=7;CIGAR=1M1D1M;DP=7;DPB=4.66667;DPRA=0;EPP=10.7656;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=56.8571;MQMR=0;NS=1;NUMALT=1;ODDS=14.3092;PAIRED=0.857143;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=249;QR=0;RO=0;RPL=1;RPP=10.7656;RPPR=0;RPR=6;RUN=1;SAF=7;SAP=18.2106;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=del;technology.ILLUMINAHiSeq1500=1   GT:DP:RO:QR:AO:QA:GL    1/1:7:0:0:7:249:-22.7657,-2.10721,0

**Comment by holtgrewe** [comment]
Empty annotations can be OK in several cases.

Here, however, there was a bug and it is fixed in #169.
