### ISSUE TITLE
isIntronic() in VariantEffect has incorrect definition of intronic

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#171]
isIntronic

    public boolean isIntronic()

    Returns:
        true if equal to CODING_TRANSCRIPT_INTRON_VARIANT or NON_CODING_TRANSCRIPT_EXON_VARIANT.

This shoud be "or NON_CODING_TRANSCRIPT_INTRON_VARIANT"

**Comment by holtgrewe** [comment]
:+1:
