### ISSUE TITLE
Concurrency problems in VariantContextAnnotator due to AnnotationCollector not being thread-safe

### ISSUE THREAD

**Issue by julesjacobsen** [charite/jannovar#199]
Using the VariantContextAnnotator in a servlet without synchronising calls to buildAnnotations() leads to incredibly varied annotations for a variant context. In general Jannovar strives for thread-safety through the use of immutable collections and local scoping/stateless classes, but this one completely falls flat on its face, which is why it came as a surprise!

Another thing - why is this class marked as final? The 'final' keyword on a class simply means no-one can extend it which is just irritating for users, it does not confer any immutability from the perspective of a class instance. Please remove this and other cases where classes are marked 'final' unless there is a real need for it.

If in the other-hand thread-safety hasn't been aimed for - you should really spell it out in the README, in which case, I let you off.

RTFM FTW!

**Comment by julesjacobsen** [comment]
I think this could be mitigated by doing this to VariantAnnotator:
```java
    #This should be moved from an instance variable...
    final private AnnotationCollector annovarFactory = new AnnotationCollector(20);

    #to a local variable inside of
    public VariantAnnotations buildAnnotations(GenomeVariant change) throws AnnotationException {
    ...

    # This is the issue - If one thread hasnt finished annotating things then another enters buildAnnotations() it will call clearAnnotationLists and the annotations will be lost. 
    this.annovarFactory.clearAnnotationLists();

    #Why not simply call new? Like this:
    AnnotationCollector annovarFactory = new AnnotationCollector(20);
    
    ...
    }

#then pass in annovarFactory as an argument to the methods it is accessed by:
    private void buildSVAnnotation(AnnotationCollector annovarFactory, GenomeVariant change, TranscriptModel transcript) throws AnnotationException {
		annovarFactory.addStructuralAnnotation(new StructuralVariantAnnotationBuilder(transcript, change).build());
	}
```

Then there should be no need to synchronise anything in AnnotationCollector as it is all kept in a local scope and not visible to seperate threads.

**Comment by julesjacobsen** [comment]
Actually thinking a little further - why is there a AnnotationCollector.clearAnnotationLists() method at all? This should be removed and the clean-up left to the GC. This class is incredibly simple and yet a bit of a mess:

```java
    public AnnotationCollector(int initialCapacity) {
	#WTF! initialCapacity is never used!
        this.annotationLst = new ArrayList<Annotation>();
        this.geneSymbolSet = new HashSet<String>();
    }
```
```java
    #nonononon
    public void clearAnnotationLists() {...}
```
```
    # This is a bug waiting to happen - 
    private int annotationCount;

    #Because in *all* cases when an annotation is added to the annotationLst, annotationCount++ is also called.
    public void addIntergenicAnnotation(Annotation ann) {
		this.annotationLst.add(ann);
		this.hasIntergenic = true;
		this.annotationCount++;
	}

    # *except* from here:
    public void addNcRNASplicing(Annotation ann) {
		// String s = String.format("%s", ann.hgvsDescription);
		this.hasNcRna = true;
		// ann.setVariantAnnotation(s); // TODO(holtgrew): necessary?
		this.annotationLst.add(ann);
        # missing  this.annotationCount++; is this a bug or deliberate?
	}

  
    public int getAnnotationCount() {
		return this.annotationCount;
        # should be return annotationLst.size();
	}

```

**Comment by julesjacobsen** [comment]
@pnrobinson - Can you say wether the missing this.annotationCount++; in addNcRNASplicing is a mistake or deliberate? This is key to the refactoring I'd suggest.

```java
    public void addNcRNASplicing(Annotation ann) {
        // String s = String.format("%s", ann.hgvsDescription);
        this.hasNcRna = true;
        // ann.setVariantAnnotation(s); // TODO(holtgrew): necessary?
        this.annotationLst.add(ann);
        # missing  this.annotationCount++; is this a bug or deliberate?
    }
```

**Comment by julesjacobsen** [comment]
@pnrobinson @holtgrewe @visze 

I've fixed the concurreny issue and in the process it seems that the AnnotationCollector class has outstayed its welcome and has been out-evolved by the rest of the new Jannovar code. 90% of the code is completely unsed and when you look at how it's actually used you eventually conclude that it can simply be replaced by an ArrayList! Do any of you have any institutional/historical knowledge to confirm this?

**Comment by holtgrewe** [comment]
@julesjacobsen Thanks for all your comments, I'll have a detailed look and comment tomorrow.

**Comment by holtgrewe** [comment]
Hi Jules, thanks for all your comments and your work, this is a good catch!

However, I have to say it was hard to trace through your changes so in #204, I have completely removed AnnotationCollector as it is not necessary any more IMO. This should get rid of the thread safety problem, I think.

Did I miss anything else from your changes?

BTW: Everything is `final` in Jannovar also because I did not want to have to put too much thinking in how to make classes extensible. Rather, I think that modern Java IDEs give you nice code generation facilities for creating wrappers were necessary which is more appropriate for Jannovar.

Please close this if #204 contains the necessary patches

**Comment by julesjacobsen** [comment]
Cheers for incorporating the fix, Manuel. Those were all the changes I suggested - I only deprecated the AnnotationCollector in order to honour the semantic versioning principals, but actually you don't subscribe to them so removing the AnnotationCollector is definitely the better option.

**Comment by holtgrewe** [comment]
Hi Jules, I consider AnnotationCollector not to be part of the Jannovar API (package level visibility only) so removing it does not change the interface as far as I am concerned. Glad I got all of your changes!

**Comment by visze** [comment]
Thanks a lot @julesjacobsen and @holtgrewe 

You are amazing!

(sorry I had no time)

**Comment by julesjacobsen** [comment]
Thank-you @visze, you are very welcome!
