### ISSUE TITLE
feature request: list exon in HGVS code

### ISSUE THREAD

**Issue by petkraw** [charite/jannovar#206]
For validation it is quite handy to list the exon in which the mutation is placed. This is not necessary in HGVS format. However, I think in brackets it is allowed to list additional info:
<accession number>.<version number>(<gene symbol>):<sequence type>.<variant description>
e.g. NM_001204.3(exon1):c.94G>C

**Comment by holtgrewe** [comment]
Could you point me to where this is written? I could not find this being allowed.

When annotating VCF, the `ANN` info value already contains the exon in one of the columns.

Please reopen if this does not help.
