### ISSUE TITLE
NullPointerException on ExAC variants

### ISSUE THREAD

**Issue by kevinwang1975** [charite/jannovar#211]
When running Jannovar 0.16 on ExAC variants, the following cause NullPointerException because Annotation.transcript is null.

Code in VariantContextAnnotator.applyStandardAnnotations(VariantContext vc, List<VariantAnnotations> annos) line 244.

Command line: java -Xms4g -Xmx4g -jar jannovar-cli-0.16.jar annotate -d data/hg19_refseq.ser -i data.vcf

1	6157591	A	C
1	6526153	C	T
1	19071422	A	G
1	19071423	G	A
1	46165783	A	G
1	154234094	T	TGGTGTGAATGTC
1	155912624	G	A
1	248513014	A	G
1	248617072	A	G
1	248617073	G	A
2	46707811	C	CGGCAGCACGAGGTGGTGATGGAGCAGCTGCAGCGGGAGT
2	62728393	G	A
2	160832586	A	T
2	176965488	G	T
2	178494128	T	C
2	220075209	G	A
2	233412780	A	C
3	97869162	G	A
3	98217475	A	G
3	150644355	G	A
4	44705178	A	T
4	94693648	G	A
4	128851898	A	G
4	152212605	A	G
5	35875688	A	AAGTG
5	35875690	G	GTGAGTGTT
5	35904770	C	A
5	140183256	A	T
5	140223350	A	G
5	140251120	G	T
5	140742138	A	G
5	140780151	A	G
5	140790232	G	C
5	140795294	G	A
5	179264198	A	G
5	180582889	G	A
6	4995281	G	A
6	26055969	G	A
6	29275432	A	G
6	30954257	T	TCAGCATAGCCACCAACTCTGAGTCCAGCACAACCTCCAGTGGGGC
6	43021966	C	A
6	43273622	G	C
6	43589813	C	T
6	47650421	G	A
6	90605819	A	G
6	110944578	G	A
6	132874859	A	G
7	140244583	G	C
7	143748429	G	A
7	143748430	A	G
8	53853454	A	G
8	144656956	G	A
9	19376254	C	A
9	107267503	A	T
9	107332410	G	A
9	107457743	A	G
9	125316440	G	C
9	125563351	G	A
10	94675642	T	TTGAAGAAGAGGATGAGAA
10	96612671	A	C
11	1651644	T	TGCTGCTGCCAGTCCAGCTGCTGTAAGCCCA
11	4904112	G	A
11	5021160	A	G
11	5969524	A	G
11	6221415	A	C
11	11373490	G	A
11	48239290	G	A
11	48347481	A	T
11	51516210	A	T
11	55111663	A	C
11	55419314	A	G
11	55419315	G	T
11	55433571	A	G
11	55563975	G	A
11	55579877	A	G
11	55607214	A	C
11	55873457	A	G
11	55890787	G	A
11	56044094	A	G
11	56044095	G	A
11	56144029	G	T
11	56432093	A	T
11	57983194	A	C
11	64940688	A	C
11	75442330	G	A
11	89451039	A	G
11	121061515	A	G
11	123811280	G	C
11	123894654	A	G
11	123901265	G	A
12	2904298	G	GCGCGGAGATGACAGC
12	48866842	G	A
12	55524559	G	A
12	55642010	A	G
12	55715322	A	G
13	28009781	T	C
14	19378573	A	T
14	20216528	A	G
14	20444724	A	G
14	20586597	G	A
15	43653272	T	G
15	66190298	C	T
15	78826012	A	G
15	79051876	G	A
15	84908899	C	CGTGAACAGGAGGAGAGGCTACGTGAACAGGAGGAGAGGCTGT
16	67973788	C	T
17	3101741	A	G
17	4442734	C	T
17	5442913	A	G
17	61994564	G	A
17	63206780	A	G
17	80207455	G	A
18	6138205	G	A
19	617225	G	A
19	3542733	A	G
19	6426363	C	G
19	15905805	G	A
19	21720843	G	A
19	45854853	C	T
19	49526127	G	A
19	50455170	G	T
19	55098535	A	T
19	56499279	G	A
20	3653453	G	T
20	10604026	A	C
21	31538242	T	C
21	31973586	A	G
21	31988944	A	G
21	32007779	G	A
21	47611881	A	T
22	23401594	A	G
22	24984214	C	A
22	51123087	C	T
X	130678974	A	G
X	133379807	A	T
X	154292310	T	C

**Comment by visze** [comment]
Sorry for the late response. There were some errors parsing the refseq data. See also issue #198 
We changed the refSeq gff parser (see #210) and I tested some of your positions with this fix. I get no errors. We will roll out this fix in v0.17. Right now you can test the actual develop branch if your issues are fixed.

**Comment by holtgrewe** [comment]
Should be fixed in 0.17.
