### ISSUE TITLE
VariantEffect#getSequenceOID does not always return correct Ontology ID

### ISSUE THREAD

**Issue by roland-ewald** [charite/jannovar#215]
For example, `VariantEffect.MNV.getSequenceOID()` returns `SO:0001583` (http://www.sequenceontology.org/browser/current_svn/term/SO:0001583), but should return `SO:0002007` (http://www.sequenceontology.org/browser/current_svn/term/SO:0002007).

The SO IDs in the javadocs for the enum values are correct, just the strings returned in the `switch` statement of `VariantEffect#getSequenceOID` are wrong.

**Comment by visze** [comment]
Thank you Roland.
I merged the pull request. Please note that we will not roll out a new version with this fix (e.g.0.16.1). We are close to release version 0.17. Your fix will be included there.

**Comment by roland-ewald** [comment]
Hi Max, thanks for the quick feedback and merge!

Don't worry update the release cycle, we have a wrapper to take care of this for now :-)

Looking forward to 0.17; keep up the great work!
