### ISSUE TITLE
Support offline compilation from sources and do not touch my $HOME

### ISSUE THREAD

**Issue by mmokrejs** [charite/jannovar#218]
Hi,
  I would like to prepare a package for jannovar in Gentoo Linux but there are several blockers:

1. The build process runs as unprivileged user, in a separate directory and I have no way to fiddle with ~/.m2/settings.xml to set the proxy trickery.
2. Anyway, all files should be available for download before compile phase (so need to set the proxy in step 1). So, what is needed to download except https://github.com/charite/jannovar/archive/v0.16.tar.gz ?
3. Please rename https://github.com/charite/jannovar/archive/v0.16.tar.gz to https://github.com/charite/jannovar/archive/jannovar-0.16.tar.gz

Thank you

**Comment by holtgrewe** [comment]
Dear @mmokrejs 

1. I have no idea how else to do this, please consult the Maven community.
2. Please look how other Gentoo Linux packages approach this with Maven projects, I don't know exactly what you mean.
3. The naming scheme is based on the naming schema for tags recommended by Github. I am not convinced that we should change this.

We recommend using the prebuilt JARs from Maven central.

- http://search.maven.org/remotecontent?filepath=de/charite/compbio/jannovar-cli/0.16/jannovar-cli-0.16.jar
- https://repo1.maven.org/maven2/de/charite/compbio/jped-cli/0.16/jped-cli-0.16.jar

Thank you

**Comment by mmokrejs** [comment]
Hi Manuel,
   thank you for a quick answer. Well, there are hardly a few packages in Gentoo using maven, almost all packages incidentally are based on Apache ant instead.

  So, what does "mvn" or some other application try to download during "mvn package" or "mvn install" steps? Why cannot I fetch it directly and notably, beforehand?

  The build system can files files, but in another step, and the file can be conveniently kept on a mirror machine, etc. Ideally, the file should be included in the tar.gz file.

Thank you,
Martin

**Comment by holtgrewe** [comment]
Hi Martin,

`mvn package` will download all Jannovar dependencies recursively (which is a *lot*). They all go into somewhere below `~/.m2`. The maven system includes something like a package management system for Java, so I don't know whether you will be able to untangle this from the Gentoo package management system up to a sensible degree.

Please consult either an expert for Maven or the Gentoo build system. These are questions that are independent of Jannovar itself.

Cheers

**Comment by mmokrejs** [comment]
Definitely, the other mvn-based packages do not fetch anything. Maven is installed as a separate package and in other cases it does not need to fiddle with downloading anything. Because of that, nobody needed to create the http proxy file either IMHO.

I already did look around for somebody more experienced with Maven but seems too few people really use it. Gentoo tries to avoid binary packages as much as possible, because they simply do not work on some architectures.

Could your IDE output also build.xml for Apache ant? That would be ideal. ;-)

**Comment by holtgrewe** [comment]
We are directly writing Maven `pom.xml` files independent of any IDE.

**Comment by holtgrewe** [comment]
Also, this is Java JAR files, they are architecture independent.

**Comment by mmokrejs** [comment]
For completeness, here is the full build.log file from Gentoo, showing what is being downloaded and where the automated process fails.

[build.txt](https://github.com/charite/jannovar/files/330431/build.txt)

**Comment by visze** [comment]
I guess the error is not about maven. It tries to create a dir in the root directory but it failed doing so. Maybe some rights issue?

**Comment by mmokrejs** [comment]
"Compilation" of every package is run in a sanbox, with ordinary user privileges, and in the end if everything went OK, a root process merges the installation from a `$DESTDIR` to a "root" or "relocated" filesystem. Thefore, all kinds of shellscripts touching your system get declined.

Also, any downloads during configure/compile/install stages are forbidden.

It is the case of the .m2 system, trying to access `$HOME`, hence the `SANDBOX VIOLATION`.

There is absolutely no reason to download anything during install step. The files to be "installed" should be just placed into their destination tree structure (still inside a sandbox, in this case /scratch/var/tmp/portage/sci-biology/jannovar-0.16/image/).

The is a lot of work in Gentoo packages to undo maven stuff and switching to ant:

https://github.com/gentoo/gentoo/blob/master/dev-lang/scala/scala-2.11.7-r1.ebuild

Seems one can just override some values from the maven's `build.xml` and **use Apache ant to do the work instead**:
https://github.com/gentoo/gentoo/blob/master/dev-java/jnr-posix/jnr-posix-3.0.10.ebuild
https://github.com/gentoo/gentoo/blob/master/dev-java/slf4j-api/slf4j-api-1.7.7.ebuild
https://github.com/gentoo/gentoo/blob/master/dev-java/jdbc-postgresql/jdbc-postgresql-9.4_p1206.ebuild

**Comment by sba1** [comment]
Am 2016-06-23 23:37, schrieb mmokrejs:
> Seems one can just override some values from the maven's build.xml and
> USE APACHE ANT TO DO THE WORK INSTEAD:

Yes, Maven is not supported by Gentoo Java Packaging. Please refer to:

https://wiki.gentoo.org/wiki/Gentoo_Java_Packing_Policy

**Comment by holtgrewe** [comment]
Good luck, we will not be able to offer any support here.

**Comment by mmokrejs** [comment]
Finally I got to tweak the Gentoo package recipe file, it builds now although it fetches the 95MB of maven's dependencies. I pushed it now to science overlay as https://cgit.gentoo.org/proj/sci.git/commit/sci-biology?id=3bd45176e875ab2b69e36a4d430dbb4b5410fb3d . However, users must enable the package themselves due to the 95MB of deps being fetched on each re-install attempt.

Am I right only these two jar files are supposed to be installed?
```
jannovar-cli/target/jannovar-cli-0.16.jar
jped-cli/target/jped-cli-0.16.jar
```

Are these included in the above jar files? (so no need to install them as separate files?)
```
jannovar-hgvs/target/jannovar-hgvs-0.16.jar
jannovar-htsjdk/target/jannovar-htsjdk-0.16.jar
jannovar-core/target/jannovar-core-0.16.jar
jannovar-filter/target/jannovar-filter-0.16.jar
jannovar-inheritance-checker/target/jannovar-inheritance-checker-0.16.jar
```

**Comment by visze** [comment]
In the cli jars the command-line interface is implemented (jannovar-cli for annotation, jped-cli for filtering variants using a pedigree and a mode of inheritance) 

If the core etc jar is included depends on how you package the cli jars. Normally they are in a lib folder. But they are needed because they have the core functionality. E.g. if you only want to use jannovar as library for annotation in you code you need only the core jar (maybe additional the htsjdk or the hgvs jars).

**Comment by mmokrejs** [comment]
So you say you advise users to move/install on their system just these three jar files?

jannovar-cli/target/jannovar-cli-0.16.jar
jped-cli/target/jped-cli-0.16.jar
jannovar-core/target/jannovar-core-0.16.jar

My question was whether the functionality in say jannovar-inheritance-checker/target/jannovar-inheritance-checker-0.16.jar is already packed into e.g. jannovar-cli/target/jannovar-cli-0.16.jar or jped-cli/target/jped-cli-0.16.jar.

IMHO this should be stated clearly in a README file or INSTALL file.

**Comment by visze** [comment]
So if you use maven (`mvn package`) as recommended in the [manual](http://jannovar.readthedocs.io/en/master/install.html) two files per package are created. For example the `jannovar-cli-0.17.jar` includes all libraries (jannovar and others like htsjdk). There is also a file `original-jannovar-cli-0.17.jar` which contains only the source files of the specific package.

Jannovar is, first of all, created as library for your java programs. If you use maven it is really simple to specify which package you need and they are automatically downloaded from maven central. We created an extra command line package (jannovar-cli) to provide the some functions from the command line (please note that jped-cli is part of jannovar-cli since 0.17).
