### ISSUE TITLE
HG38 Download Exception: File not found

### ISSUE THREAD

**Issue by bearbob** [charite/jannovar#222]
I tried downloading the datasources for hg38/ucsc and encountered this error:

    ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
    Options
    verbosity: 1
    dataSourceFiles: [bundle:///default_sources.ini]
    dataSourceNames: [hg38/ucsc]
    downloadPathdata
    HTTP proxy: null
    HTTPS proxy: null
    FTP proxy: null
    Downloading/parsing for data source "hg38/ucsc"
    INFO Downloading data...
    INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/knownCanonical.txt.gz
    INFO Creating directory data/hg38/ucsc
    [==================================================]   100%
    INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/knownGene.txt.gz
    [==================================================]   100%
    INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/knownGeneMrna.txt.gz
    [==================================================]   100%
    INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/kgXref.txt.gz
    [==================================================]   100%
    INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/knownToLocusLink.txt.gz
    [==================================================]   100%
    INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz
    [==================================================]   100%
    INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/Assembled_chromosomes/chr_accessions_GRCh38.p2
    ERROR: ERROR: Problem downloading file: sun.net.ftp.FtpProtocolException: CWD genomes:550 genomes: No such file or directory

    de.charite.compbio.jannovar.datasource.FileDownloadException: ERROR: Problem downloading file: sun.net.ftp.FtpProtocolException: CWD genomes:550 genomes: No such file or directory

        at de.charite.compbio.jannovar.datasource.FileDownloader.copyURLToFileThroughURL(FileDownloader.java:257)
        at de.charite.compbio.jannovar.datasource.FileDownloader.copyURLToFile(FileDownloader.java:83)
        at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:81)
        at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:41)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:111)

A similar error occurs for the other sources (refseq and ensembl). For hg19 it works as intended.

**Comment by visze** [comment]
Hi bearbob,

thanks for the BUG. We have problems with the instability of the resources (see #194). The upstream resources changes their files regularly. We will provide a general workaround in one of the next releases.

To resolve your issue you have to download the source code, edit file `jannovar-cli/src/main/resources/default_sources.ini` and change the file `ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/Assembled_chromosomes/chr_accessions_GRCh38.p2` to `ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/Assembled_chromosomes/chr_accessions_GRCh38.p7`

Then recompile jannovar and generate a new java package. The easiest way to create the package is by using maven: `mvn install package`

**Comment by holtgrewe** [comment]
Should be fixed in 0.17 release
