### ISSUE TITLE
Refurbish command line interface

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#226]
The apache CLI is a bit dusted and the structure of the help is unstructured.

IMO, something like argparse4j (ported version of the awesome Python `argparse` library) looks like a good candidate.

**Comment by visze** [comment]
vote against it. commons-cli does the job perfectly (and it is well known). The only thing is that we did not implement it well. So we can refurbish the interface but I please stick to commons-cli.

**Comment by pnrobinson** [comment]
I am a fan off "if it ain't broke don't fix it"...so is there something that we just cannot do now that somebody is asking for?
