### ISSUE TITLE
1/2 genotype incorrectly considered as HOM_ALT

### ISSUE THREAD

**Issue by julesjacobsen** [charite/jannovar#285]
Genotype does not take into account genotypes which could come from a multi-sample VCF where there are multiple alternative alleles from different samples leading to 1/1, 1/2, 2/2 etc. genotypes.

In these cases Genotype reports as being a homozygous alt, where it should be heterozygous. HTSJDK refers to this as Genotype.isHetNonRef() which is why the jannovar-inheritance-checker module doesn't suffer from this.

**Comment by visze** [comment]
closed by pull request #288
