### ISSUE TITLE
wrong cast!

### ISSUE THREAD

**Issue by visze** [charite/jannovar#289]
[Here](https://github.com/charite/jannovar/blob/develop/jannovar-htsjdk/src/main/java/de/charite/compbio/jannovar/mendel/bridge/VariantContextMendelianAnnotator.java#L170) the payload is set with an variantcontext.

And [here](https://github.com/charite/jannovar/blob/develop/jannovar-htsjdk/src/main/java/de/charite/compbio/jannovar/mendel/bridge/VariantContextMendelianAnnotator.java#L85) the payload is casted to an integer without instance checking!

**Comment by bengyunfu** [comment]
So did you have any ideas to fix this? I can't read JAVA so I can't fix it myself.

**Comment by visze** [comment]
@holtgrewe is working on that issue
