### ISSUE TITLE
stop lost variants buggy?

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#304]
For example

chr2    85322745    .    A    G    209.77    PASS    AC=1;AF=0.500;AN=2;ANN=G|stop_lost|HIGH|TGOLN2|10618|transcript|NM_001206840.1|Coding|4/4|c.1363T>C|p.(*455Gln)|1697/10279|1363/1443|455/481||;BaseQRankSum=-0.623;ClippingRankSum=0.000;DP=10;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.000;QD=20.98;ReadPosRankSum=1.348;SOR=0.473    GT:AD:DP:GQ:PL    0/1:2,8:10:50:238,0,50

I checked this with Mutalyzer as "NM_001206840.1:c.1363T>C"and got 
 "T not found at position 1697, found C instead."

The stop codon appears to be further downstream
Here is another stop lost annotation that appears to be wrong according to Mutalyzer

chr20    37137934    .    A    G    194.77    PASS    AC=1;AF=0.500;AN=2;ANN=G|stop_lost|HIGH|MROH8|140699|transcript|NM_152503.5|Coding|13/25|c.1525T>C|p.(*509Gln)|1633/78363|1525/3129|509/1043||;BaseQRankSum=0.615;ClippingRankSum=0.000;DP=19;ExcessHet=3.0103;FS=1.871;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.000;QD=10.25;ReadPosRankSum=-1.514;SOR=1.402    GT:AD:DP:GQ:PL    0/1:10,9:19:99:223,0,232

**Comment by holtgrewe** [comment]
Good catch. This is caused by Jannovar 0.20 trusting the user variant more than the transcripts. Gosh!

I am changing this behaviour in #308 for the 0.21 release.

```
$ java -jar jannovar.jar annotate-pos -d hg38_refseq.ser --show-all -c 'chr2:85322745A>G' -c 'chr20:37137934A>G'
#change	effect	hgvs_annotation	messages
chr2:85322745A>G	SPLICE_REGION_VARIANT+CODING_TRANSCRIPT_INTRON_VARIANT,SPLICE_REGION_VARIANT+CODING_TRANSCRIPT_INTRON_VARIANT,SYNONYMOUS_VARIANT,SYNONYMOUS_VARIANT	TGOLN2:NM_001206844.1:c.1135-4T>C:p.?,TGOLN2:NM_006464.3:c.1309-4T>C:p.?,TGOLN2:NM_001206840.1:c.1363C>C:p.(=),TGOLN2:NM_001206841.1:c.1322C>C:p.(=)	.;.;WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT;WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT
chr20:37137934A>G	MISSENSE_VARIANT,MISSENSE_VARIANT,MISSENSE_VARIANT	MROH8:NM_152503.5:c.1525G>C:p.(E509Q),MROH8:NM_213631.2:c.1525G>C:p.(E509Q),MROH8:NM_213632.2:c.1420G>C:p.(E474Q)	WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT;WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT;WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT
```

@pnrobinson @visze @martenj I think we should make a 0.21 release for the book with this change and other changes we might need in between. Just use the current develop branch after merging (nothing else should really change). What do you thin.

**Comment by holtgrewe** [comment]
@pnrobinson please close if you think this resolves this particular issue
