### ISSUE TITLE
HGVS to VCF error

### ISSUE THREAD

**Issue by nvteja** [charite/jannovar#305]
Hello,

First of all, thanks a lot for creating and maintaining this tool. 

I am trying to test the HGVS to VCF conversion command, but I see that is always right shifting the deletions to one base right. Here is an example

HGVS: NM_018136.4:c.567_569del
the correct VCF representation for this HGVS should be: 
1 197112812 . GCTC G

but here is what the Jannovar's hgvs-to-vcf outputs intsead

1 197112813 . GCCTGC GC

the hg19.fa file I used is the same file that was used to call the "1 197112812 . GCTC G" variant, so its not the hg19.fa file issue.

The weird part is that the reference string that the hgvs-to-vcf outputs : "GCCTGC" does not match the genome string at that position. The correct genomic string is GCTCC. 

This looks like a bug.  Can you please look into it?

Thank you,
Teja.

**Comment by holtgrewe** [comment]
Should be fixed once #325 is merged.

Please reopen if you see anything else suspicious. I'll try to fix it in a shorter time then.
