### ISSUE TITLE
 getTmByGeneSymbol

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#347]
In JannovarData, the documentation for getTmByGeneSymbol seems to ba a copy-paste error from the method getTmByAccession. 
It would also be good to document here which transcriptModel is chosen for a gene model, since there are usually multiple transcripts per gene.
    

    public com.google.common.collect.ImmutableMultimap<String,TranscriptModel> getTmByGeneSymbol()

    Returns:
        map from transcript accession to TranscriptModel instance.

**Comment by holtgrewe** [comment]
Fixing comment in #429. Note that this function returns a multimap, thus all transcripts for any gene symbol are returned.
