### ISSUE TITLE
Support for hg19/refseq interim FASTA format

### ISSUE THREAD

**Issue by roland-ewald** [charite/jannovar#353]
## Problem

In Feburary, the NCBI published [a new "interim" alignment of RefSeq transcripts against hg19](https://www.ncbi.nlm.nih.gov/books/NBK430989/), which can be found here: ftp://ftp.ncbi.nlm.nih.gov/genomes/Homo_sapiens/GRCh37.p13_interim_annotation/

However, the [new FASTA file with the transcript RNA](ftp://ftp.ncbi.nlm.nih.gov/genomes/Homo_sapiens/GRCh37.p13_interim_annotation/interim_GRCh37.p13_rna.fa.gz) has header line with a different format.

For example:
````
>NM_000014.5 Homo sapiens alpha-2-macroglobulin (A2M), transcript variant 1, mRNA
````
instead of
````
gi|66932946|ref|NM_000014.4| Homo sapiens alpha-2-macroglobulin (A2M), mRNA
````

as it would be expected by `de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser#loadFASTA`, which splits the ID by `|`.

Thus, attempting to load the interim hg19 release into Jannovar yields these kinds of error:

````
ERROR ID NM_003445.3 in FASTA did not have 4 fields
````

## How to reproduce

To reproduce, run `java -Xms4G -Xmx4G -jar jannovar-cli-0.23-SNAPSHOT.jar download -s hg19.ini -d hg19/interim` with `hg19.ini` (also attached, [hg19.ini.zip](https://github.com/charite/jannovar/files/1104712/hg19.ini.zip)) being:

````
; New interim alignment:
[hg19/interim]
type=refseq
alias=MT,M,chrM
chromInfo=http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/chromInfo.txt.gz
chrToAccessions=ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.105/Assembled_chromosomes/chr_accessions_GRCh37.p13
chrToAccessions.format=chr_accessions
gff=ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/GRCh37.p13_interim_annotation/interim_GRCh37.p13_knownrefseq_alignments_2017-01-13.gff3.gz
rna=ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/GRCh37.p13_interim_annotation/interim_GRCh37.p13_rna.fa.gz
````

## Solution

Since the main purpose of splitting the header line seems to be the retrieval of the transcript accession number, I would suggest to either make the splitting character (right now, hardcoded with `|`), the index where to expect the accession (right now, hardcoded as `3`), and the expected number of tokens after splitting (right now, hardcoded as `5`) configurable in the `data_source.ini`. 

Alternatively, the transcript accession could be retrieved via a regular expression instead.

_I'm happy to provide a PR, but would need feedback regarding the implementation approach._

**Comment by holtgrewe** [comment]
Hi Roland,

sorry for the delay.

Thank you for the notification.

I think changing this will be very simple.

1. Change line 140 in `RefSeqParser.java` to detect which format is present. Here, I would like to see a check for the old format and for the new format, the accession should start with `[NX]M_` or so (I think they added more naming patterns), to make parsing detect possible problems.
2. Add the new format as `hg19_refseq_interim` for now.
3. Adjust the CHANGELOG file.

@visze I think we will need to also version the transcripts besides versioning the reference. Changing this to `hg19/refseq.81`, for example. This is more important for ENSEMBL and GRCh38, I guess.

I would be very happy to review and accept a PR against the `develop` branch.

Cheers,
Manuel

**Comment by roland-ewald** [comment]
Hi Manuel,

Thanks for looking into this. 
I will try to come up with a PR against `develop` over the weekend.

Cheers,
Roland

**Comment by roland-ewald** [comment]
Hi Manuel,

Sorry this somehow slipped through the cracks. Let me know if you need any additional changes.

Best regards,
Roland

**Comment by visze** [comment]
is now in version v25!
