### ISSUE TITLE
Null pointer in AnnotationLocation.getRankType()

### ISSUE THREAD

**Issue by ielis** [charite/jannovar#355]
Hi everybody,
I've been recently trying to use Jannovar in a java project where I need to filter VariantContext objects depending on their position in exon or intron. My approach was to use the value of `AnnotationLocation.RankType` enum like this:
```java
class VariantFilter {

    @Autowired
    private JannovarData jannovarData;

    private VariantContextAnnotator annotator = new VariantContextAnnotator(jannovarData.getRefDict(), jannovarData.getChromosomes());

    public boolean test(VariantContext vc) throws InvalidCoordinatesException {
        List<VariantAnnotations> anns = annotator.buildAnnotations(vc);
        return anns.stream().anyMatch(VariantFilter::passes);
    }

    static boolean passes(VariantAnnotations va) {
        if (va.hasAnnotations()) {
            Annotation highest = va.getHighestImpactAnnotation();
            GenomeVariant variant = va.getGenomeVariant();

            AnnotationLocation.RankType rankType = highest.getAnnoLoc().getRankType(); // NullPointerException is being thrown here
            if (rankType.equals(AnnotationLocation.RankType.EXON)) {
                return true;
            }
        }
        return false;
    }
}
```

Unfortunately, I can't avoid getting **NullPointerException** when testing some intergenic variant (e.g. rs761275, 1:207972154A>C). The null pointer is coming from calling `getRankType()` method of the `AnnotationLocation` class and there is no way to find out if the `RankType` is null before the NullPointer is actually thrown.

I was wondering if:
- there is some better way to filter variants by their exonic/intronic localisation
- or if the behaviour of `getRankType()` could be modified such that the method would not throw the NullPointer.

Thank you very much in advance,
Daniel

**Comment by visze** [comment]
Hi Daniel,

as defined in the `Annotation.class` it can be `null` when the if the variant is not even nearby a TranscriptModel ( I think around 20Kb away from it). E.g. your example is intergenic.
I see that it is maybe not the best idea to use `null` here. A rank like undefined or INTERGENIC might be much better.
In your case I think you can remove every variant with a RankType of null.

Cheers
Max

**Comment by ielis** [comment]
Hi Max,
after reading the `Annotation.class` docs I figured out that I've made a silly mistake - I thought the `null` is coming from `getRankType()` but it was actually coming from `getAnnoLoc()` which is (as you wrote) `null` for intergenic variant distant from TranscriptModel.
Now the code works perfectly. Thank you very much for help and congratulations to the hyperSMURF paper!

Cheers
Daniel
