### ISSUE TITLE
Mitochondrial inheritance

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#362]
I would like to implement a mitochondrial filter. At the simplest level (for a single exome or genome), all we need to do is filter for genes that are localized to the MT. For pedigrees, we basically just need a rule that the gene needs to be MT and no instance of affected father to affected child was observed. 
This is the classic definition (from GeneReviews):
A family history in which males and females are affected, affected females transmit the disease to all their children, and affected males do not transmit the disease to their children suggests mitochondrial inheritance.

However, because of heteroplasmy, things are not always so simple, and given the variability of mitochondrial phenotypes, I do not think we want a hard filter that affected mother to unaffected child rules out mitochondrial inheritance. 

@holtgrewe @julesjacobsen @visze It would be great to implement this soon and test it in the Exomiser. I would be glad to do this in form of a pull request, but if anybody else is already working on it or could do this more quickly than myself it would also be great to skype. We would like to add this for the 100K analysis.

**Comment by julesjacobsen** [comment]
Will need a ```de.charite.compbio.jannovar.mendel.ModeOfInheritance.MITOCHONDRIAL``` to make a start on this in Exomiser. Currently using the ```de.charite.compbio.jannovar.mendel.bridge.VariantContextMendelianAnnotator``` to do the annotating.

**Comment by visze** [comment]
If we keep it simple it will be really easy to implement. Otherwise I suggest two filters. A strict one and a loose one.

The simple one will be a more strict (but we can use the suggested "not-filter" from @pnrobinson 

* inheritance only from mother
* Only affected can have the mutation
* No enforcement of inheritance from affected to mother child.

**Comment by pnrobinson** [comment]
Given the fact that mitochondrial mutations can be present any where from 0-100% in some cell, I am worried that if we make the filter too strict we will have false negative results. Since there are only 37 genes involved, we are unlikely to get lots of false positives. Could we try to implement the really simple filter (mitochondrial gene) and see how things work?

**Comment by pnrobinson** [comment]
I am going to make a branch called Mitochondrion. Please contact me if anybody else wants to work on this.

**Comment by pnrobinson** [comment]
I have added a new class in jannovar-core, in the package mendel.impl called InheritanceCheckerMT that implements the mitochondrial inheritance check. I have added corresponding constants and modifications to the classes ModeOfInheritance, SubModeOfInheritance and MendelianInheritanceChecker. 

I tried to set up a test class called InheritanceCheckerMTSinglePersonTest

however, I was then not able to perform testing:
Information:java: Errors occurred while compiling module 'jannovar-hgvs'
Information:javac 1.8.0_144 was used to compile java sources
Information:16.09.17 09:54 - Compilation completed with 100 errors and 12 warnings in 5s 636ms
/home/peter/IdeaProjects/jannovar/jannovar-hgvs/src/main/java/de/charite/compbio/jannovar/hgvs/parser/Antlr4HGVSParserListenerImpl.java
Error:(36, 64) java: package de.charite.compbio.jannovar.hgvs.parser.Antlr4HGVSParser does not exist
Error:(37, 64) java: package de.charite.compbio.jannovar.hgvs.parser.Antlr4HGVSParser does not exist
Error:(38, 64) java: package de.charite.compbio.jannovar.hgvs.parser.Antlr4HGVSParser does not exist
(... etc...)

Allof the classes in package de.charite.compbio.jannovar.hgvs.parser; are showing this kind of error. I am not sure where to go from here. I have checked in all of my code in the mitochondrion branch, it would be great if somebody could take a look.

**Comment by pnrobinson** [comment]
@visze @holtgrewe  I have just checked in the test class InheritanceCheckerMTSinglePersonTest and InheritanceCheckerMTSmallTest
I am uncertain how to connect this with the rest of Jannovar, please give input!

**Comment by julesjacobsen** [comment]
Do you mean how to open a pull request to get this merged in?

By the way - a stylistic point for using the Streams API with Boolean functions:

In InheritanceCheckerMT [lines 47 and 49](https://github.com/charite/jannovar/blob/d6d22eb19e441c873ac40612f99751aa2afbb94c/jannovar-core/src/main/java/de/charite/compbio/jannovar/mendel/impl/InheritanceCheckerMT.java#L47-L49)

```java
        compatibleCalls = mitoCalls.filter(this::isCompatibleSingleton);
    else
        compatibleCalls = mitoCalls.filter(this::isCompatibleFamily);

...

private boolean isCompatibleSingleton(GenotypeCalls calls) {
    return calls.getNSamples() > 0; // return true if there is at least one called variant.
}

private boolean isCompatibleFamily(GenotypeCalls calls) {
	return (affectedsAreCompatible(calls) && parentsAreCompatible(calls) );
}
```

The Boolean return type can be replaced with a typed ```java.util.function.Predicate```

```java
        compatibleCalls = mitoCalls.filter(isCompatibleSingleton());
    else
        compatibleCalls = mitoCalls.filter(isCompatibleFamily());

...

private Predicate<GenotypeCalls> isCompatibleFamily() {
	return calls -> (affectedsAreCompatible(calls) && parentsAreCompatible(calls));
}

private Predicate<GenotypeCalls> isCompatibleSingleton() {
	return calls -> calls.getNSamples() > 0; // return true if there is at least one called variant.
}
```

**Comment by holtgrewe** [comment]
IMO, returning a predicate adds and unnecessary layer of complexity and the current implementation is stylistically better because it's simpler.

**Comment by pnrobinson** [comment]
In answer to Jules, the code is finished locally and about ten test cases are passed, but I think some other places of the code need to be modified to be able to use mitochondrial filtering in the actual app. If somebody can give me a hand here, great, otherwise I can probably figure this out and will make a PR next week or so.

**Comment by holtgrewe** [comment]
@pnrobinson I'll post a list of source locations that should be changed for this today or tomorrow.

**Comment by visze** [comment]
And don't forget to modify the documentation/manual an changelog

Am 19.09.2017 12:22 schrieb "Manuel Holtgrewe" <notifications@github.com>:

@pnrobinson <https://github.com/pnrobinson> I'll post a list of source
locations that should be changed for this today or tomorrow.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/charite/jannovar/issues/362#issuecomment-330496435>,
or mute
the thread

**Comment by pnrobinson** [comment]
With the latest changes, the MT annotator appears to be working. I have checked the variants here
https://www.mitomap.org/foswiki/bin/view/MITOMAP/ClinicalPhenotypesPolypeptide using the hg38 UCSC data:

 $ java -jar jannovar-cli/target/jannovar-cli-0.23.jar annotate-pos -d data/hg38_ucsc.ser -c 'chrM:13514A>G'
$ java -jar jannovar-cli/target/jannovar-cli-0.23.jar annotate-pos -d data/hg38_ucsc.ser -c 'chrM:14487T>C'
$ java -jar jannovar-cli/target/jannovar-cli-0.23.jar annotate-pos -d data/hg38_ucsc.ser -c 'chrM:10197G>A'
 $ java -jar jannovar-cli/target/jannovar-cli-0.23.jar annotate-pos -d data/hg38_ucsc.ser -c 'chrM:10158T>C'
=> All results were correct

=> I think that we will not be able to use the hg37 UCSC data for mitochondrial inheritance because of inconsistencies in the data source. This is yet another reason to have to community upgrade to hg38
=> I will make a PR.

**Comment by visze** [comment]
See # #379
