### ISSUE TITLE
import de.charite.compbio.jannovar.hgvs.parser.Antlr4HGVSParser.*

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#364]
In branch Master there does not seem to be a class that corresponds to 
import de.charite.compbio.jannovar.hgvs.parser.Antlr4HGVSParser and this is causing a compile error.

**Comment by visze** [comment]
This class is automatically generated via Antlr.

If you run `mvn package`

you will find the file under: `jannovar-hgvs/target/generated-sources/antlr4/de/charite/compbio/jannovar/hgvs/parser`

**Comment by pnrobinson** [comment]
Ah! sure, I did not think of this and was using an intellij build. Works fine now.
