### ISSUE TITLE
New feature: allow prioritization of chrX RefSeq transcripts in PAR

### ISSUE THREAD

**Issue by roland-ewald** [charite/jannovar#372]
## Problem

RefSeq transcripts of genes located in the pseudo-autosomal regions (PAR) on chrX and chrY have unique mRNA IDs in the GFF3 file provided by the NCBI, but only one of them can be included into Jannovar's `JannovarData` (as it contains a `Map<String, TranscriptModel>` that allows per-accession lookup, but that would have to be changed to `Map<String, List<TranscriptModel>>` etc., which is a major change and probably not worth the trouble). 

Currently, transcripts on chrY are implicitly prioritized over transcripts on chrX, as the GFF files provided by the NCBI list the features 'in order', and the chrY entries simply override their chrX counterparts in [`RefSeqParser#loadFASTA`](https://github.com/charite/jannovar/blob/2d3137beeceece2421deb2899400d541a9adf1c8/jannovar-core/src/main/java/de/charite/compbio/jannovar/impl/parse/refseq/RefSeqParser.java#L124).

This is unfortunate, because the PAR on chrY is often hard-masked (i.e. all reads get aligned to the PAR on chrX), so that none of the about 60 transcripts that are affected by this can be used.

## How to reproduce

Download `hg19/refseq` or `hg19/refseq_interim`. Manually load `JannovarData` and observe that, for example, [`NM_000451.3`](https://www.ncbi.nlm.nih.gov/nuccore/NM_000451.3) has `chrY` as location and not `chrX`:

````java
JannovarData result = new JannovarDataSerializer("jannovar/hg19_refseq_interim.ser").load();
System.out.println(tmByAccession.get("NM_000451.3").getChr());
````

## Suggested solution

There does not seem to be a simple solution for this, as the assumption of accession ID uniqueness is rather fundamental. The best option seem to be to 

a) warn users about transcripts affected by this during the generation of `JannovarData` and 

b) allow them to change the prioritization via a parameter in `default_sources.ini`, in case the alignment and variant calling was done with a reference genome with a hard-masked PAR on chrY.

This would also mean that the default behavior does not get changed, but users would be able to adjust the reference dictionary to their needs. Please find [sample `LOGGER` output](https://github.com/charite/jannovar/files/1510377/sample_log_output_par_refseq.txt) attached.

## Open Questions

I am preparing a PR for this, but this is currently focused on RefSeq only: does this problem also occur for other transcript sets? It seems [Ensembl could have the same issue](http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000185960;r=X:624344-659411).

**Comment by visze** [comment]
thx roland for highlighting this issue. We should definitely try to find a solution for this. And as you pointed out this might not be simple. Your proposed solution might work. I am not really a fan of Warnings to the users (because normally they will overlook them). But a **documented default behavior** with an option to change it sounds good to me.

Perfect that you already prepared a PR. That a good base to discuss this. I will have a deeper look at it next week (hopefully).

**Comment by roland-ewald** [comment]
@visze I agree regarding the warnings. One alternative implementation to the PR woukd be to explicitly define a chromosome order (preference) in case of multiple locations per transcript (right now this implicit in the ordering of the GFF features, something that a user may not be aware of), and then simply allow a re-definition of that order. This would be more general than my implementation, but maybe also a little more complex (and I hope this is only really necessary for the PAR transcripts, so it may be too generic as well). In any case, thank you for looking into this!

**Comment by pnrobinson** [comment]
There are  genes with multiple copies on other chromosomes for which similar issues apply--multiple locations per transcript. I think mainly these are nc genes. Also, as the new genome build becomes more established, there will be about 1000 genes with locations on alternate scaffolds. It would be good to figure out a general strategy for dealing with this.

**Comment by roland-ewald** [comment]
@pnrobinson thank you for your input! These are very good points. 

Given this situation, I suggest that I re-work the PR to:
- make `contigOrder` an option that can be specified for any data source (not just RefSeq)
- document that `contigOrder` will be defined per default as: `chr1, .., chr22, chrX, chrY, chrM` (however, this will change the default behavior of jannovar when using RefSeq GFF files --- maybe it is better to have `chr1, .., chr22, chrY, chrX, chrM`, i.e. `chrY` before `chrX` defined for the RefSeq data sources in `default_sources.ini`)
- implement and test this for `RefSeqParser` (I may need help with the others, but will have a look first; this should not be too difficult)
- print out a *summary* (one line, log-level `INFO`) of the number of 'collisions', i.e. how many transcript locations were discarded overall


The inclusion of locations on alternative scaffolds could later be included, and could be optional, e.g. via parameter like `includeAlternateScaffolds=true` (how to prioritize them in a concise way may also be a problem).

Does this make sense? Or is it simpler to allow multiple transcript copies (i.e. a `List<TranscriptModel>` for each accession), one for each location?
