### ISSUE TITLE
HGVS to VCF test failed

### ISSUE THREAD

**Issue by jianl** [charite/jannovar#387]
On macOS Sierra 10.12.6
Running HGVS to VCF test as suggested in the manual
```java -jar jannovar-cli-0.23.jar hgvs-to-vcf -d data/hg19_refseq.ser -i examples/small_hgvs.lst -o examples/small_hgvs.vcf -r ~/work/ref/hg19/hg19.fa```

and failed with error message
```
ANTLR Tool version 4.6 used for code generation does not match the current runtime version 4.7
ANTLR Tool version 4.6 used for code generation does not match the current runtime version 4.7
Exception in thread "main" htsjdk.samtools.SAMException: Query asks for data past end of contig
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:220)
	at de.charite.compbio.jannovar.htsjdk.GenomeRegionSequenceExtractor.load(GenomeRegionSequenceExtractor.java:45)
	at de.charite.compbio.jannovar.hgvs.bridge.NucleotideChangeToGenomeVariantTranslationImplBase.getGenomeSeq(NucleotideChangeToGenomeVariantTranslationImplBase.java:39)
	at de.charite.compbio.jannovar.hgvs.bridge.NucleotideDeletionToGenomeVariantTranslationImpl.run(NucleotideDeletionToGenomeVariantTranslationImpl.java:47)
	at de.charite.compbio.jannovar.hgvs.bridge.NucleotideChangeToGenomeVariantTranslator.translateNucleotideVariantToGenomeVariant(NucleotideChangeToGenomeVariantTranslator.java:88)
	at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.translate(ProjectTranscriptToChromosome.java:227)
	at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.processFile(ProjectTranscriptToChromosome.java:166)
	at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.run(ProjectTranscriptToChromosome.java:76)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:64)```

**Comment by visze** [comment]
Hi jiani!

thank you for this issue. The only problem is, that I cannot reproduce this error. I tried the same with the actual development version and the test version. Both run trough and I get the output:

```

```

**Comment by jianl** [comment]
Hi visze,

Thanks a lot for your reply.

I do have fai index for the reference. To make sure I got it right, I re-downloaded samtools-1.6
http://www.htslib.org/download/

installed it, and ran faidx on the reference again. I also made a soft link "hg19.fai" to "hg19.fa.fai" to make sure it can be recognized.

However, I still got the same error
"Query asks for data past end of contig"
Please advice.

Thanks,
Jian

**Comment by visze** [comment]
Okay. But it seems to be a problem of the reference file. The error comes from the htslib and not directly from jannovar.

So it seems that that your reference fasta is maybe corrupted. One sequence of a contig is to short. Can you run the command:
```
cat ~/work/ref/hg19/hg19.fa | grep ">"
```
to show the contigs that are present in the fasta file. Maybe you can count also the number of nucleotides for chromosome 1. The sequence should have the size of `249250621`. At least longer than `879482` (because this is the last variant we are looking for).

Maybe you have to download the reference again.

**Comment by jianl** [comment]
hm, I think I might know what the problem possibly is. The hg19.fa I have was downloaded years ago, and for each contig it is in the format of 50b per line. Is that format not accepted by jannovar?

**Comment by visze** [comment]
No this this should not be a problem.

Can you run the previous command I posted. And then also this one:
```
samtools faidx ~/work/ref/hg19/hg19.fa "chr1:879317-879317" "chr1:879482-879482"
```

(if `chr1` is your contig 1; otherwise replace `chr1` with `1`)

**Comment by jianl** [comment]
results for $ cat ~/work/ref/hg19/hg19.fa | grep ">"
>chrM
>chr1
>chr2
>chr3
>chr4
>chr5
>chr6
>chr7
>chr8
>chr9
>chr10
>chr11
>chr12
>chr13
>chr14
>chr15
>chr16
>chr17
>chr18
>chr19
>chr20
>chr21
>chr22
>chrX
>chrY
>chr1_gl000191_random
>chr1_gl000192_random
>chr4_ctg9_hap1
>chr4_gl000193_random
>chr4_gl000194_random
>chr6_apd_hap1
>chr6_cox_hap2
>chr6_dbb_hap3
>chr6_mann_hap4
>chr6_mcf_hap5
>chr6_qbl_hap6
>chr6_ssto_hap7
>chr7_gl000195_random
>chr8_gl000196_random
>chr8_gl000197_random
>chr9_gl000198_random
>chr9_gl000199_random
>chr9_gl000200_random
>chr9_gl000201_random
>chr11_gl000202_random
>chr17_ctg5_hap1
>chr17_gl000203_random
>chr17_gl000204_random
>chr17_gl000205_random
>chr17_gl000206_random
>chr18_gl000207_random
>chr19_gl000208_random
>chr19_gl000209_random
>chr21_gl000210_random
>chrUn_gl000211
>chrUn_gl000212
>chrUn_gl000213
>chrUn_gl000214
>chrUn_gl000215
>chrUn_gl000216
>chrUn_gl000217
>chrUn_gl000218
>chrUn_gl000219
>chrUn_gl000220
>chrUn_gl000221
>chrUn_gl000222
>chrUn_gl000223
>chrUn_gl000224
>chrUn_gl000225
>chrUn_gl000226
>chrUn_gl000227
>chrUn_gl000228
>chrUn_gl000229
>chrUn_gl000230
>chrUn_gl000231
>chrUn_gl000232
>chrUn_gl000233
>chrUn_gl000234
>chrUn_gl000235
>chrUn_gl000236
>chrUn_gl000237
>chrUn_gl000238
>chrUn_gl000239
>chrUn_gl000240
>chrUn_gl000241
>chrUn_gl000242
>chrUn_gl000243
>chrUn_gl000244
>chrUn_gl000245
>chrUn_gl000246
>chrUn_gl000247
>chrUn_gl000248
>chrUn_gl000249

and $samtools faidx ~/work/ref/hg19/hg19.fa "chr1:879317-879317" "chr1:879482-879482"
>chr1:879317-879317
C
>chr1:879482-879482
G

**Comment by visze** [comment]
great! Thank you! 
But now I have no clue anymore :-( You reference seems to be fine. You can try to download them again. But now I am not sure if this solves the issue.

How did you receive or generate the `jannovar-cli-0.23.jar` file? Maybe you can try to use the actual `0.24` release. But I am still not sure if this will help.

**Comment by xiamaz** [comment]
I am currently also trying to run this test. The process runs though, although I am getting different vcf results, than the ones in readthedocs.
My results for the hgvs sequences:
```
NM_018136.4:c.567_569del
NM_152486.2:c.305+42_305+43insCCCT
XM_005244727.1:c.799C>T
XM_005244727.1:c.964G>C
```
are
```
##fileformat=VCFv4.2
##ALT=<ID=ERROR,Description="Error in conversion">
##FILTER=<ID=PARSE_ERROR,Description="Problem in parsing original HGVS variant string, written out as variant at 1:g.1N>N">
##INFO=<ID=ERROR_MESSAGE,Number=1,Type=String,Description="Error message">
##INFO=<ID=ORIG_VAR,Number=1,Type=String,Description="Original HGVS variant string from input file to hgvs-to-vcf">
##contig=<ID=1,length=249250621>
##contig=<ID=2,length=243199373>
##contig=<ID=3,length=198022430>
##contig=<ID=4,length=191154276>
##contig=<ID=5,length=180915260>
##contig=<ID=6,length=171115067>
##contig=<ID=7,length=159138663>
##contig=<ID=8,length=146364022>
##contig=<ID=9,length=141213431>
##contig=<ID=10,length=135534747>
##contig=<ID=11,length=135006516>
##contig=<ID=12,length=133851895>
##contig=<ID=13,length=115169878>
##contig=<ID=14,length=107349540>
##contig=<ID=15,length=102531392>
##contig=<ID=16,length=90354753>
##contig=<ID=17,length=81195210>
##contig=<ID=18,length=78077248>
##contig=<ID=19,length=59128983>
##contig=<ID=20,length=63025520>
##contig=<ID=21,length=48129895>
##contig=<ID=22,length=51304566>
##contig=<ID=X,length=155270560>
##contig=<ID=Y,length=59373566>
##contig=<ID=MT,length=16569>
##contig=<ID=GL000207.1,length=4262>
##contig=<ID=GL000226.1,length=15008>
##contig=<ID=GL000229.1,length=19913>
##contig=<ID=GL000231.1,length=27386>
##contig=<ID=GL000210.1,length=27682>
##contig=<ID=GL000239.1,length=33824>
##contig=<ID=GL000235.1,length=34474>
##contig=<ID=GL000201.1,length=36148>
##contig=<ID=GL000247.1,length=36422>
##contig=<ID=GL000245.1,length=36651>
##contig=<ID=GL000197.1,length=37175>
##contig=<ID=GL000203.1,length=37498>
##contig=<ID=GL000246.1,length=38154>
##contig=<ID=GL000249.1,length=38502>
##contig=<ID=GL000196.1,length=38914>
##contig=<ID=GL000248.1,length=39786>
##contig=<ID=GL000244.1,length=39929>
##contig=<ID=GL000238.1,length=39939>
##contig=<ID=GL000202.1,length=40103>
##contig=<ID=GL000234.1,length=40531>
##contig=<ID=GL000232.1,length=40652>
##contig=<ID=GL000206.1,length=41001>
##contig=<ID=GL000240.1,length=41933>
##contig=<ID=GL000236.1,length=41934>
##contig=<ID=GL000241.1,length=42152>
##contig=<ID=GL000243.1,length=43341>
##contig=<ID=GL000242.1,length=43523>
##contig=<ID=GL000230.1,length=43691>
##contig=<ID=GL000237.1,length=45867>
##contig=<ID=GL000233.1,length=45941>
##contig=<ID=GL000204.1,length=81310>
##contig=<ID=GL000198.1,length=90085>
##contig=<ID=GL000208.1,length=92689>
##contig=<ID=GL000191.1,length=106433>
##contig=<ID=GL000227.1,length=128374>
##contig=<ID=GL000228.1,length=129120>
##contig=<ID=GL000214.1,length=137718>
##contig=<ID=GL000221.1,length=155397>
##contig=<ID=GL000209.1,length=159169>
##contig=<ID=GL000218.1,length=161147>
##contig=<ID=GL000220.1,length=161802>
##contig=<ID=GL000213.1,length=164239>
##contig=<ID=GL000211.1,length=166566>
##contig=<ID=GL000199.1,length=169874>
##contig=<ID=GL000217.1,length=172149>
##contig=<ID=GL000216.1,length=172294>
##contig=<ID=GL000215.1,length=172545>
##contig=<ID=GL000205.1,length=174588>
##contig=<ID=GL000219.1,length=179198>
##contig=<ID=GL000224.1,length=179693>
##contig=<ID=GL000223.1,length=180455>
##contig=<ID=GL000195.1,length=182896>
##contig=<ID=GL000212.1,length=186858>
##contig=<ID=GL000222.1,length=186861>
##contig=<ID=GL000200.1,length=187035>
##contig=<ID=GL000193.1,length=189789>
##contig=<ID=GL000194.1,length=191469>
##contig=<ID=GL000225.1,length=211173>
##contig=<ID=GL000192.1,length=547496>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       197112812       .       GCTC    G       .       .       .
1       866511  .       C       CCCCT   .       .       .
1       879317  .       C       T       .       .       .
1       879482  .       G       C       .       .       .
```
These are generated using this command:
`java -jar jannovar-cli-0.24.jar hgvs-to-vcf -d data/hg19_refseq.ser -i small_hgvs.lst -o small_hgvs.vcf -r human_g1k_v37.fasta`
I have generated faidx and dict using samtools 1.7. I am using jannovar 0.24 as a binary.

**Comment by visze** [comment]
@xiamaz can you open a new issue with your post?

**Comment by mutundis** [comment]
I had this problem too and solved it by using a GRCh37 assembly reference file (with chromosomes named  "1" rather than "chr1" etc) instead of an hg19 assembly reference file (which is what you have).

**Comment by jianl** [comment]
Interesting ... thanks @mutundis!
I think then it should be named accordingly to GRCh37 instead of hg19.

**Comment by holtgrewe** [comment]
Please reopen if this persists.
