### ISSUE TITLE
Amino acid codes are always three letters

### ISSUE THREAD

**Issue by messersc** [charite/jannovar#396]
Hi,

I noticed that amino acid codes are always three letters, no matter if you specify `--3-letter-amino-acids` or not. I am using Jannovar 0.24 from conda.

```
jannovar annotate-vcf -XX:MaxHeapSize=5g  -i small.vcf -o small.annotated.vcf -d /fast/projects/cubit/current/static_data/app_support/Jannovar/0.22/hg19_ensembl.ser

jannovar annotate-vcf -XX:MaxHeapSize=5g --3-letter-amino-acids  -i small.vcf -o small.annotated.3letter.vcf -d /fast/projects/cubit/current/static_data/app_support/Jannovar/0.22/hg19_ensembl.ser
```

```diff
diff small.annotated.*
5c5
< ##jannovarCommand=annotate-vcf --3-letter-amino-acids -i small.vcf -o small.annotated.3letter.vcf -d /fast/projects/cubit/current/static_data/app_support/Jannovar/0.22/hg19_ensembl.ser
---
> ##jannovarCommand=annotate-vcf -i small.vcf -o small.annotated.vcf -d /fast/projects/cubit/current/static_data/app_support/Jannovar/0.22/hg19_ensembl.ser
```

### Expected behaviour

I would expect one letter amino acid codes when not setting `--3-letter-amino-acids` .

**Comment by visze** [comment]
HGVS (see http://varnomen.hgvs.org/recommendations/general) claims to use the three letter code as "preferred" option. We will use the one letter code as default with the additional `--3-letter-amino-acid` command.

So you are right. jannovar does not act like expected

**Comment by visze** [comment]
see next release
