### ISSUE TITLE
hg38 datasets in default_sources.ini point to inactive links

### ISSUE THREAD

**Issue by bpow** [charite/jannovar#402]
The hg38 datasets point to links (like ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/Assembled_chromosomes/chr_accessions_GRCh38.p7 ) that are no longer present on NCBI servers (as of about 2018.03.31).

These either need to be changed to reference the current files (which are at patch level 12)-- eg `s/GRCh38.p7/GRCh38.p12`, *or* the .p7 files should be referenced from the ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.108/ directory on the NCBI site.

I'd be happy to send a patch, but don't know which of these two would be preferable (would switching to .p12 cause other problems?

**Comment by bpow** [comment]
The RefSeq rna.fa.gz header line format has changed (again... see #353), so the newest annotation relase (version 109, based on GRCh38.p12) until this is addressed. #403 or #404 would suffice.

**Comment by visze** [comment]
good catch. I think we should fix this ASAP!

I will use the archive version first. Here we do not have to change the parser. But we should definitely address the new version and the new header.

**Comment by visze** [comment]
reading now trough #371, #403 and #404. I am a bit lost :-)

**Comment by bpow** [comment]
The confusion is all my fault...

The short version is that #403 builds upon/supplants #371 with a method that identifies the format by the initial string on a header line, and #404 is an alternative that recognizes all of the same formats using a regular expression. I don't feel strongly about one approach or the other, just wanted to point out both possibilities.

So, the options are #403 xor #404

**Comment by visze** [comment]
I will go for #403 because the changelog is documented :-)

**Comment by visze** [comment]
PR #403 closes this issue
