### ISSUE TITLE
Disabling ANN field escaping doesn't work

### ISSUE THREAD

**Issue by CarlosBorroto** [charite/jannovar#412]
I'm trying to use the `annotate-vcf` argument `--no-escape-ann-field`. However, the `ANN` field is still getting escaped.

Looking at what I think is the relevant code I see a hard-coded `true` value is been used.
https://github.com/charite/jannovar/blob/develop/jannovar-core/src/main/java/de/charite/compbio/jannovar/annotation/Annotation.java#L295-L297

I confirmed switching it to `false` outputs un-escaped annotation. I'm trying to get familiar with the code base to see if I can fix this myself and submit a PR.

Thanks,
Carlos

**Comment by holtgrewe** [comment]
Fixed in e3760238f180fff4b06d96500293a092a637aad5, will be part of next release.
