### ISSUE TITLE
Jannovar versioning

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#416]
The current version of the master branch is 26-SNAPSHOT.
I am wondering if the master branch shouldn't be constrained not to have the SNAPSHOT tag.
e.g., https://stackoverflow.com/questions/5901378/what-exactly-is-a-maven-snapshot-and-why-do-we-need-it

**Comment by iimpulse** [comment]
Also.. Maven central is 0.27. It's a bit confusing landing on the github page and seeing a different version both in commits and readme. Is master the most recent branch? If not setting develop as default might be desired.

**Comment by holtgrewe** [comment]
I'm sorry. Should be fixed now.
