### ISSUE TITLE
structural variants

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#418]
Add support to Jannovar for structural variant calls in VCF files.
Support calls such as will emerge from MANTA:
https://github.com/Illumina/manta/blob/master/docs/userGuide/README.md#manta-vcf-reporting-format
Note that MANTA is currently VCF 4.1, but the latest version is 4.3 -- Jannovar should support also 4.3

**Comment by holtgrewe** [comment]
See #428. Regarding VCF v4.3, HTSJDK does not support it. Also see https://github.com/broadinstitute/gatk/issues/2092
