### ISSUE TITLE
java 11

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#421]
Should we be thinking about providing support for Java 11? I am guessing that most software that uses Jannovar is still Java 8, but that many or even most groups (including our own) and planning on moving to Java 11 in 2019.

**Comment by pnrobinson** [comment]
Java 11 is 99% backwards compatible, and I do not see any big problems. It can be faster and better with GC, although it is hard to predict how much. I am currently using the Java 11 compiler at level 8 for some projects, but have not yet begun to really take advantage of some of the interesting new constructs (e.g., var is like C++ auto and there is an interesting module system that would allow better encapsulation than with package-privacy etc).

**Comment by julesjacobsen** [comment]
and there are new immutable collections via ```List.of()``` and ```Set.of()``` like Guava. New HTTP2 support, Reactive streams support (Java 9), the Module system (Java 9), the language release name e.g. 1.8 -> 9 -> 10 -> 11! New release schedule with LTS releases every 2 years.  JVM licencing changes (beware!) too.

https://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html
https://www.oracle.com/technetwork/java/javase/10-relnote-issues-4108729.html
https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html

**Comment by holtgrewe** [comment]
Don't forget https://aws.amazon.com/corretto/.

Current Travis CI should have all currently supported Java versions starting from 8. Right now, I don't see a reason to move forward with Java for Jannovar as a library. Any user is free to use Java 11+.
