### ISSUE TITLE
Apply Google style Java formatting throughout project

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#424]
@roland-ewald @julesjacobsen 

We plan to apply and enforce automatic Google style Java formatting throughout the project. We'll try to get the current PRs merged before this. Make sure to scream loudly in case you have local branches that you intended to merge at some point.

**Comment by julesjacobsen** [comment]
So long as this happens post PR-merge, that's fine. Thanks for the forewarning!

**Comment by holtgrewe** [comment]
@julesjacobsen did you see that I merged your changes in another PR?

**Comment by roland-ewald** [comment]
@holtgrewe thanks for the heads-up; no problem from my side.

**Comment by holtgrewe** [comment]
Giving up on this.
