### ISSUE TITLE
splice region variant PutativeImpact: MODERATE vs. LOW?

### ISSUE THREAD

**Issue by bpow** [charite/jannovar#439]
In Jannovar, a splice_region_variant has PutativeImpact of MODERATE (it is the lowest MODERATE impact SO term).

The putative impact table in the [ANN specification](http://snpeff.sourceforge.net/VCFannotationformat_v1.0.pdf), splice_region_variant is listed at LOW. The ANN specification lists this table as "suggested", so this difference does not "violate" the spec, but it is discordant from what is described there.

Is this difference in Jannovar vs. the spec intentional?

**Comment by holtgrewe** [comment]
Interesting. Actually the document lists the `splice_region_variant` as both `LOW` **and** `MODERATE` [VEP](https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html) lists it as `LOW`. If you look at the ANN spec, it mentions `splice_branch_variant` below which does not occur in the text above. VEP does not know about `splice_branch_variant`... I'd be willing to make it consistent with the VEP implementation of the spec if you point me at the location in the VEP source code. It is my impression that VEP is the major predictor these days (I still see Jannovar being available as a Java library as a major reason for it to stick around ;)

I don't have strong feeling either way as you will want to have more refined variant grading a la CADD anyway.

**Comment by bpow** [comment]
Ha! I hadn't noticed it was listed twice... too bad there isn't a repo with an issues list for the ANN specification :smile:

As for where this is in the VEP source, it is located in the ensembl-variation repo which is a dependency of VEP. Specifically in [Bio::EnsEMBL::Variation::Utils::Constants.pm](https://github.com/Ensembl/ensembl-variation/blob/70d2777fc85fc501513be5d6cad9024ef2b0f0e0/modules/Bio/EnsEMBL/Variation/Utils/Constants.pm), lines 424-440 are how VEP describes/handles splice_region_variant (SO:0001630). On line 431, it is listed as having `impact` of `LOW`.

**Comment by pnrobinson** [comment]
These categories are not a useful way of prioritizing variants in the splice region anyway, and we might as well be consistent with VEP.

**Comment by visze** [comment]
closed by #442
