### ISSUE TITLE
request to move hgnc_complete download to ini file

### ISSUE THREAD

**Issue by mmcneill123** [charite/jannovar#451]
Right now, the JANNOVAR tool has a requirement to download ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt
This path is hard-coded in the tool. 
At my institution "ftp://" protocols are generally blocked. Would you be willing to move the source path for this file into the ini file so that I can change "ftp://" to "http://", which passed through our firewall?

**Comment by holtgrewe** [comment]
Will be added to next release.
