### ISSUE TITLE
Bug in converting from hgvs ins/ dup into VCF

### ISSUE THREAD

**Issue by mmcneill123** [charite/jannovar#452]
Good morning,
I've been doing testing using JANNOVAR to convert variants from transcript-oriented HGVS format into genomic oriented VCF files. 
My tests with deletions and SNPs have been successful, but I've gotten unexpected results with insertions and duplication. Would you please take a look at the two examples below? 
I generated by expected result by manual interrogation of NCBI's genome browser and verifying the variant conversion using https://variantvalidator.org

Conversions are in GRCh38 (human) genome. 

Duplication:
NM_001129765.1:c.696dupG
Expected X:152867579 A>AG
Observed: X:152867580 A>AG

Insertion:
NM_001129765.1:c.696_697insT
Expected: X:152867580 G>GT
Observed: X:152867580 A>AT

**Comment by holtgrewe** [comment]
Using RefSeq, Jannovar currently only consider the mRNA sequence from RefSeq and not the reference genome. This needs to be changed, I guess.

**Comment by holtgrewe** [comment]
Will be fixed in next release.
