### ISSUE TITLE
Quick-start documentation link broken

### ISSUE THREAD

**Issue by cmdcolin** [charite/jannovar#459]
https://doc-openbio.readthedocs.io/projects/jannovar/en/master/quickstart.html

"Download the current stable release from our GitHub project by clicking here."

Refers to the github releases but doesn't seem to be inserting the version number. Since I am looking at the master branch's readthedocs maybe that is the reason but this is navigable via google

**Comment by visze** [comment]
Thank you for finding this issue. I fixed it in the actual development branch. It will be corrected in the next release.

**Comment by visze** [comment]
There is a general issue with RTD. It does not build newer versions. I created a new ticket for that: #460
