### ISSUE TITLE
building the rat genome under v0.33

### ISSUE THREAD

**Issue by mmcneill123** [charite/jannovar#464]
Hi Manuel, 

Thanks for taking a look at the rat genome database a couple of weeks ago. I've now tried to replicate your success, but I am unable to do so in full.
First, I tried building from version 0.32, and this built successfully.
```
java -jar ${file_path}jannovar-cli-0.32.jar download -d rn6/refseq
```
Next, I tried to build it with 0.33
```
java -jar ${file_path}jannovar-cli-0.33.jar download -d rn6/refseq
```
but the internal ini was missing the new faMT key. (Can you add this to the documentation?)

I next tried building the .ser file from 0.32 with my own ini file, in which I added the allowNonCodingNm key. 
```
java -jar ${file_path}jannovar-cli-0.32.jar download -s ${file_path}my_refseq.ini -d rn6/refseq
```
This worked!

I then added the faMT key to my ini, and I tried the same command with the 0.33 version, but I ran into an error:
```
Options
JannovarDownloadOptions [downloadDir=data, getDataSourceFiles()=[bundle:///default_sources.ini, /srv/shiny-server/HDR_design_tool/HDR_tool/lib/external/my_refseq.ini], isReportProgress()=true, getHttpProxy()=null, getHttpsProxy()=null, getFtpProxy()=null, geneIdentifiers=[], outputFile=]
Downloading/parsing for data source "rn6/refseq"
INFO Downloading data...
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/GFF/ref_Rnor_6.0_top_level.gff3.gz
INFO Downloaded file ref_Rnor_6.0_top_level.gff3.gz looks like a valid gzip'ed file
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/RNA/rna.fa.gz
INFO Downloaded file rna.fa.gz looks like a valid gzip'ed file
INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/rn6/database/chromInfo.txt.gz
INFO Downloaded file chromInfo.txt.gz looks like a valid gzip'ed file
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/Assembled_chromosomes/chr_accessions_Rnor_6.0
INFO Downloading https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?save=file&db=nuccore&report=fasta&id=110189714
INFO Downloading http://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt
INFO Building ReferenceDictionary...
INFO Parsing transcripts...
INFO Loading feature records
INFO Determined GTF/GFF file version to be GFF3
Exception in thread "main" java.lang.NullPointerException
        at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.loadTranscriptModels(RefSeqParser.java:368)
        at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.run(RefSeqParser.java:99)
        at de.charite.compbio.jannovar.datasource.RefSeqJannovarDataFactory.parseTranscripts(RefSeqJannovarDataFactory.java:36)
        at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:110)
        at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:43)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)
```
here's the ini file I'm currently using:

```
[rn6/refseq]
type=refseq
alias=MT,M,chrM
allowNonCodingNm=true
chromInfo=http://hgdownload.soe.ucsc.edu/goldenPath/rn6/database/chromInfo.txt.gz
chrToAccessions=https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/Assembled_chromosomes/chr_accessions_Rnor_6.0
chrToAccessions.format=chr_accessions
gff=https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/GFF/ref_Rnor_6.0_top_level.gff3.gz
rna=https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/RNA/rna.fa.gz
faMT=https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?save=file&db=nuccore&report=fasta&id=110189714
```

Comparing the logging information for my usage of 0.33 vs the one you provided in your response to my issue #461 (Thank you!), it looks like I download the faMT tag (required in 0.33), but your example did not. Pehraps it behaved more like 0.32, which is able to build rn6?

Additional note 1: I tried our previous workaround for rn6 (issue #441), which was onlyCurated=True to try to get past the NullPointerException, but that didn't work this time.
Additional note 2: As a positive control for my proceedure, I successfully built ini and ser files for 4 other species using 0.33

Thanks for your help!
Matt

**Comment by visze** [comment]
Hi Matt!

sorry for taling so long for looking into this. This is absolutely important. Since 0.33 we have the new faMT annotation. But now it is required and it is only set for human and not for mouse, rat,.. maybe there is a species without it.

And yes. Documentation is missing! We have to do this!

@holtgrewe What was was you idea about genomes without MT and what happens with a missing faMT tag in the ini file. Right now it returns an error...

**Comment by mmcneill123** [comment]
Thanks!

**Comment by holtgrewe** [comment]
@visze @mmcneill123 I can look into this next week (this week being pretty short in Germany)

**Comment by visze** [comment]
It seems to be a lot of broken paths in the `default_sources.ini ` file. Right now I am checking everything, trying to fix every download. I am also adding the faMT file for all refseq annotations.

But this will be only a workaround because jannovar will not be able to annotate species that do not have a mitochondrion

**Comment by visze** [comment]
I am getting the same null pointer also on mm9. Not on mm10!
