### ISSUE TITLE
dup exon jumping

### ISSUE THREAD

**Issue by dulekb** [charite/jannovar#465]
I'm running into 5'/3' shifting issues with duplication events running Jannovar 0.33.  Annotating against the transcript NM_001291722.1 for the variant chr5:156721863T>TC Jannovar calls c.283dup/p.Gln95Profs*15.  The predicted effect is correct, but the variant call does not follow HGVS nomenclature.  The correct variant should be c.282dup.  The duplication is at the end of exon 4 where there are 3 C's in a row and exon 5 starts with a C.  The shift should stop at the end of exon 4 and not jump to exon 5.  See the note on LRG_199t1:c.3921dup on the page https://varnomen.hgvs.org/recommendations/DNA/variant/duplication/.

Thanks for the help!
Brittany

**Comment by visze** [comment]
Which genome build do you use?

**Comment by visze** [comment]
I think you are using hg19. 

Thank you for that issue. I have to look deeper into that. But on a first look it seems that first is the nucleotide change and the second the protein change (two different things). Here we have a frame shift because of the insertion of one C. See [HGVS](https://varnomen.hgvs.org/recommendations/protein/variant/frameshift/). So `p.Gln95Pro` is the first amino-acid affected and we have a new stop codon 15 codons later (`fs*15`). See the example `p.Gln151Thrfs*9`

**Comment by holtgrewe** [comment]
Here is what the current `develop` gives.

```
# java -jar jannovar-cli/target/jannovar-cli-0.36-SNAPSHOT.jar annotate-pos -c 'chr5:156721863T>TC' -d ../jannovar-data-0.34/hg19_refseq.ser 
Options
JannovarAnnotatePosOptions [genomicChanges=[chr5:156721863T>TC], toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=../jannovar-data-0.34/hg19_refseq.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Deserializing transcripts...
INFO Deserializing JannovarData from ../jannovar-data-0.34/hg19_refseq.ser
INFO Deserialization took 4.74 sec.
#change	effect	hgvs_annotation	messages
chr5:156721863T>TC	FRAMESHIFT_ELONGATION	CYFIP2:XM_005265885.1:c.283dup:p.(Q95Pfs*15)	INFO_REALIGN_3_PRIM
```

**Comment by holtgrewe** [comment]
I belive it's GRCh38/hg38. The following is what variant validator gives which equals Jannovar.

![image](https://user-images.githubusercontent.com/521780/121261228-bcab2a00-c8b2-11eb-8662-d75910418de6.png)

Please re-open if you disagree.
