### ISSUE TITLE
HGVS protein annotation error for deletions (may impact other mutation types e.g. ins)

### ISSUE THREAD

**Issue by wmgmm** [charite/jannovar#481]
I found this for a number of deletions and insertions.

Depending on the deleted unit, the bases after the deletion may preserve the last wildtype amino acid, even while using a different codon, so the HGVS protein annotation produced by Jannovar is incorrect.

e.g.  NM_023110.2:c.165_171delTCGGCTG
VCF Format (hg19):
8	38287386	.	CCAGCCGA	C	.	.	.

Below is the sequence context, with deleted bases in lower case:
codon 54-CTT CGC TGtcggctgC GGG ACG ATG

Jannovar produces the following cdna+protein hgvs:
NM_023110.2:c.165_171del  p.(L57Tfs*44)

The correct hgvs protein nomenclature should be:
p.(Arg56Glyfs*45)

You can check this against Mutalyzer a program for checking that reported variant comply with HGVS  
https://mutalyzer.nl/name-checker?description=NM_023110.2%3Ac.165_171delTCGGCTG
and look at the affected proteins section:
NM_023110.2(FGFR1_i001):p.(Arg56Glyfs*45)

**Comment by holtgrewe** [comment]
I can confirm that #499 fixes this problem:

```
# java -jar jannovar-cli/target/jannovar-cli-0.35-SNAPSHOT.jar annotate-pos -d jannovar-data-0.34/hg19_refseq_curated.ser -c 'chr8:38287387CAGCCGA>'
Options
JannovarAnnotatePosOptions [genomicChanges=[chr8:38287387CAGCCGA>], toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=jannovar-data-0.34/hg19_refseq_curated.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Deserializing transcripts...
INFO Deserializing JannovarData from jannovar-data-0.34/hg19_refseq_curated.ser
INFO Deserialization took 2.58 sec.
#change	effect	hgvs_annotation	messages
chr8:38287387CAGCCGA>	FRAMESHIFT_TRUNCATION	FGFR1:NM_001174063.1:c.165_171del:p.(R56Gfs*45)	.
```
