### ISSUE TITLE
Problem parsing HGVS `delins`

### ISSUE THREAD

**Issue by markwoon** [charite/jannovar#491]
I'm attempting to parse `NC_000007.14:g.32386323_32386325delGCins`, which arguably is invalid because it's missing the inserted sequence, but the parser is seeing the `GC` as the inserted sequence.

Running:
```
HGVSParser hgvsParser = new HGVSParser();
SingleAlleleNucleotideVariant variant = (SingleAlleleNucleotideVariant)
  hgvsParser.parseHGVSString("NC_000007.14:g.32386323_32386325delGCins");
System.out.println(variant.getChange().toHGVSString());
```

Produces: `32386323_32386325delinsGC`

Which is definitely wrong.

**Comment by holtgrewe** [comment]
Thanks for reporting. I'll look into this, I don't expect a too complex fix.
