### ISSUE TITLE
Error while trying to download human hg-19 reference using jannovar v 0.34 installed via bioconda

### ISSUE THREAD

**Issue by guglusharma** [charite/jannovar#495]
Getting the following error. Plz suggest a solution. Noob in the use of Linux/CLI.

$ jannovar  download -d hg19/refseq -d hg19/ucsc
Options
JannovarDownloadOptions [downloadDir=data, getDataSourceFiles()=[bundle:///default_sources.ini], isReportProgress()=true, getHttpProxy()=null, getHttpsProxy()=null, getFtpProxy()=null, geneIdentifiers=[], outputFile=]
Downloading/parsing for data source "hg19/refseq"
INFO Downloading data...
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.105/GFF/ref_GRCh37.p13_top_level.gff3.gz
ERROR: ERROR: Problem downloading file: Resource temporarily unavailable (connect failed)
de.charite.compbio.jannovar.datasource.FileDownloadException: ERROR: Problem downloading file: Resource temporarily unavailable (connect failed)
        at de.charite.compbio.jannovar.datasource.FileDownloader.copyURLToFileThroughURL(FileDownloader.java:253)
        at de.charite.compbio.jannovar.datasource.FileDownloader.copyURLToFile(FileDownloader.java:79)
        at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:83)
        at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:43)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)

Seems the link from where jannovar is trying to get the files returns a 404 error.
Do I need to update jannovar to 0.35 version? how to do that if I had taken the easy way of installing via conda?

**Comment by visze** [comment]
hi thanks for the issue,

it seems that the ftp site of ncbi, where we dowloand most of the sources, had a complete restructure. So all links are broken (again!). This causes regularly problems. We change the URLs and make a new release. But in the future we have to use something different to prevent this errors.

I keep you updated when we fixed the issue.

**Comment by visze** [comment]
we already fixed the issue in the development branch. But we need to make a new release to update conda etc.

**Comment by mm19jv** [comment]
still having this problem.

**Comment by mm19jv** [comment]
can this be patched ASAP?

**Comment by holtgrewe** [comment]
@mm19jv We already patched, tagged, and released v0.35. There is something stuck in Bioconda. Any help here is contributed.

I would welcome some understanding that we are doing this work for free besides our actual jobs. This is open source and academic software. You are welcome to provide patches and contribute!

Alternatively, contact me privately and I'll give you a quote for payed support. Alternative software packages include VEP and Annovar that you might look into as well.

**Comment by holtgrewe** [comment]
Here's the BIoconda package. https://github.com/bioconda/bioconda-recipes/pull/23151

**Comment by holtgrewe** [comment]
We now have prebuilt databases, this should fix this issue.
