### ISSUE TITLE
Problem with multiple family input

### ISSUE THREAD

**Issue by choishingwan** [charite/jannovar#5]
In the function: inputPedFileStream, it was observed that the firstline variable will always be true. Therefore, when user input a ped file with multiple family, they will all be considered to be in the family of the last sample by the inputPedFileStream function. Fortunately, this problem is captured and will causes the addIndividual function called in Pedigree.java to throw an error.

**Comment by holtgrewe** [comment]
Please check whether the problem persists in v0.12 or later and reopen ticket if necessary.
