### ISSUE TITLE
NCBI urls are out-of-date

### ISSUE THREAD

**Issue by squid-dev** [charite/jannovar#500]
Using the default values in default_sources.ini it is not possible to download hg19/ucsc or hg19/refseq. Hg19/ensembl also seems to be failing for me with a different error but I haven't investigated. It's not clear to me where the new locations are at NCBI.
e.g.:

> Problem downloading file: https://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.105/GFF/ref_GRCh37.p13_top_level.gff3.gz
de.charite.compbio.jannovar.datasource.FileDownloadException: ERROR: Problem downloading file:...

**Comment by pnrobinson** [comment]
@holtgrewe @visze @julesjacobsen 
I am wondering if it would be better to include one file with chromosome lengths as a part of the Jannovar download. I realize there are lots of problems with this approach, but our current approach is not robust. The chromosome lengths are the same for all of the flavors of a genome build. We could include this as a default that could be overridden if for some reason somebody wanted to download the file from somewhere.  Thoughts?

**Comment by julesjacobsen** [comment]
Its a great idea. The reference genome / reference dictionary needs a bit of attention to be able to parse the data from GenBank assembly report files to parse the 'assembled-molecule' rows into numbered contigs for use in Jannovar.

Last time I did a build I had to manually remove one of the two mitochondrial chromosomes present in one of the files which broke the Jannovar build.

**Comment by holtgrewe** [comment]
Dear Peter, Dear Jules;

actually Max and I would like to mirror both the "raw data" and the built/released databases on figshare or zenodo in the future to circumvent such problems... However, time is slipping through my hands and as much as I try, I don't get to working on Jannovar these days (I believe that Max has similar issues).

**Comment by pnrobinson** [comment]
@holtgrewe @visze let's start to put some files onto zenodo. Should I start a project? Also, I would suggest that we no longer support some of the older builds such as hg18. I will write a page for the read the docs about the INI files and how to set things up. Currently, most things do not work, e.g. hg19, even in the develop branch.

**Comment by holtgrewe** [comment]
@pnrobinson sounds good!
