### ISSUE TITLE
mitochondrial genetic code

### ISSUE THREAD

**Issue by smw1414** [charite/jannovar#501]
Hi, Jannovar team

I found that jannovar (0.35, refseq_curated) use standard genetic code to decode the products in chrM.   
For example, chrM:3669A>G (rs386828918 ) was annotated as stop_lost. But actually it's a synonymous variant.

**Comment by pnrobinson** [comment]
Good point, I do not think we have implemented this. See https://en.wikipedia.org/wiki/Human_mitochondrial_genetics#Genetic_code_variants.
