### ISSUE TITLE
--show-all option not properly worked

### ISSUE THREAD

**Issue by smw1414** [charite/jannovar#503]
Hi jannovar team,
I use jannovar(0.35, refseq, hg38) to annotate a position, chr10:60572463A>T, with --show-all option in vcf format. This position locates on ANK3 and should have 5 curated transcripts. However, it only output annotations of 2 transcripts. Hope you can manage to solve this issue, thanks.

**Comment by pnrobinson** [comment]
I get this:
```
$ java -jar jannovar-cli/target/jannovar-cli-0.36-SNAPSHOT.jar annotate-pos -c 'chr10:60572463A>T' -d data/hg38_refseq_curated.ser --show-all
(...)
#change	effect	hgvs_annotation	messages
chr10:60572463A>T	SPLICE_DONOR_VARIANT+CODING_TRANSCRIPT_INTRON_VARIANT,CODING_TRANSCRIPT_INTRON_VARIANT	ANK3:NM_001204404.1:c.63+2T>A:p.?,ANK3:NM_001204403.1:c.96+42723T>A:p.(=)	.;.
```
I am seeing two refseq sequences at this position
https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr10%3A60572458%2D60572467&hgsid=918065035_SDeC2iWKKe5P7q88SaELAtUMkCff
Can you provide more information about the "missing" transcripts, what are you expecting to see? At first glance, I think that the other ANK3 transcripts do not cover this genomic position.

**Comment by smw1414** [comment]
You are correct. I think I overlooked that this position may not covered by other transcripts. Thanks.
