### ISSUE TITLE
Deposit static files into Zenodo

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#513]
**Is your feature request related to a problem? Please describe.**
The download URLs turn out to be unstable. In particular, RefSeq release 105 has now moved somewhere (TM) on the NCBI servers and is not available any more at its original location.

**Describe the solution you'd like**
We should deposit a copy of all data on Zenodo.

- [x] deposit files as downloadable in Zenodo (use `-` to create sub directory like structure)
- [ ] adjust the INI files to download from there
- [x] drop support for hg18 from INI files

**Describe alternatives you've considered**
Hosting the files at another location could turn out to be unstable, so Zenodo is the best solution.

**Additional context**
BIH should have a copy of the files in the current Jannovar release on our internal mirror servers. I'll take the files from there.

**Related Tickets**
- #500 
- #497 
- #495 
- #492 
- #489 
- #464 
- #468

**Comment by holtgrewe** [comment]
CC @visze @pnrobinson

**Comment by holtgrewe** [comment]
Zenodo seems to be down right now, I'll try to attach a copy of the data here.

**Comment by holtgrewe** [comment]
OK, the files are here now inside a ZIP archive. Zenodo does not support sub directories, so we would have to put the folder structure into the file name, e.g., by replacing `/` by `-`.

https://zenodo.org/record/4906580#.YL5ExDqxWAk

**Comment by holtgrewe** [comment]
CC #504

**Comment by pnrobinson** [comment]
This is a good suggestion. Zenodo is a good choice for the download files.

**Comment by holtgrewe** [comment]
@pnrobinson what do you think about slimming down things even further:

- Provide Bash scripts for building a "data release", IOW: download upstream files and upload them into Zenodo.
- We could then attach the `.ser` files here to the releases.
- We could get rid of the code for downloading files which means less code to maintain. Instead, "download" would pull the files from Github.

**Comment by pnrobinson** [comment]
There are multiple possible ways of doing this. I think that 99% of users would appreciate things being simple and would be happy to trust us for making the ".ser" files. When we released the first version of Jannovar, the download was reliable and simple enough, but now the upstream sources seem determined to change paths often...so, yes, I think your suggestion is great

**Comment by holtgrewe** [comment]
INI files don't download from Zenodo but we have download scripts as described in the `README.md` now.
