### ISSUE TITLE
RefSeq datasets for mm11

### ISSUE THREAD

**Issue by myeelaw** [charite/jannovar#531]
Mouse mm39 (GRCm39) was released in June of 2020. Will mm11/refseq be available for download soon? 
We use Jannovar to obtain HGVS annotation regularly and it is a pain to convert them back to mm39 coordinates then run Jannovar on those each time.

Thank you in advance!

**Comment by holtgrewe** [comment]
I'm looking into this right now. RefSeq should be possible. For ENSEMBL we still have the issue of requiring HGNC gene mapping in the Java code. Supporting it will require a change to the Java code. UCSC switched away from knownGene/knownCanonical for mm39 as they don't do their own genes any more (if I understand correctly). So UCSC would not be useful anyway.

**Comment by holtgrewe** [comment]
OK, I have uploaded mm10 and mm39 builds of refseq and refseq_curated. Please reopen this ticket if you have any problems with this file. The links are in the updated README in the `master` branch.

**Comment by myeelaw** [comment]
Thank you for making this available so quickly! 

I don't see mm39 in the list when I input 
>java -jar jannovar-cli-0.36.jar db-list

Do I need to update or something?

**Comment by myeelaw** [comment]
The filename has mm10 in it (refseq_109_mm10.ser). Do you mean mm11 or m39?

**Comment by holtgrewe** [comment]
Apparently I made a mistake in the README. You can find the full list here:

- https://zenodo.org/record/5410367

You can find the updateded INI file with the data sources in the `dev` branch so the `.ser` file can be built with the v0.36. I already did this and uploaded the results to Zenodo at the URL above. There is no need to upgrade Jannovar to use this file, the file will (most probably) be compatible with v0.37.

**Comment by holtgrewe** [comment]
OK, I had a look at this again.

I put two refseq releases for mm9 (37.2 and 106). So this was correct but redundant. The refseq release for mm10 is 108 and the refseq release for mm39 is 109. I removed the outdated release for mm9 and kept mm9/106 mm10/108, mm39/109. I believe that this is correct and corresponds to the currently most recent refseq releases for the references. Also, I believe that these are the three most recent mouse reference sequence releases.

Please reopen if you think there is a mistake.

**Comment by myeelaw** [comment]
both refseq_109_mm10.ser and refseq_curated_109_mm10.ser have file size of 8KB while refseq_108_mm10.ser is about 58.9MB. I am sure I am missing something but thought to check with you first.
