### ISSUE TITLE
broken links to datasets download

### ISSUE THREAD

**Issue by myeelaw** [charite/jannovar#533]
Can you fix the links on:

https://github.com/charite/jannovar/blob/master/README.md for file names 1) refseq_109_mm10.ser and 2) refseq_curated_109_mm10.ser 

or https://zenodo.org/record/5410367#.YTpPMB0pBqt for file names 1) refseq_139_mm39.ser and 2) refseq_curated_139_mm39.ser 

Thank you!

**Comment by holtgrewe** [comment]
Thanks for the report. Could you help me spot the problem?

**Comment by myeelaw** [comment]
Can you double check if the files are fully uploaded? They appear to be less than 8kb each.
