### ISSUE TITLE
hgvs-to-vcf hanging when encountering incorrect hgvs entries

### ISSUE THREAD

**Issue by h-joshi** [charite/jannovar#539]
**Describe the bug**
hgvs-to-vcf hangs when processing a variant where the HGVS notation is invalid (In this case, the reference base is invalid)
NM_021120.3:c.*1975G>A

**To Reproduce**
Set up :
* `refseq_109_hg38.ser`
* `test.tsv` containing one entry ("NM_021120.3:c.*1975G>A")
* hg38 fasta

Run
```bash
#!/bin/sh

java -jar jannovar-cli-0.38.jar hgvs-to-vcf \
    -r Homo_sapiens_assembly38.fasta
    -d refseq_109_hg38.ser \
    -i test.tsv \
    -o test.vcf
```

Current output is
```
Options
ProjectTranscriptToChromosomeOptions [pathInputText=test.tsv, pathOutputVCF=test.vcf, pathReferenceFASTA=/project/RDS-SMS-GDT-RW/data/hg38_ref/Homo_sapiens_assembly38.fasta, toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=refseq_109_hg38.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Loading database file...
INFO Deserializing JannovarData from refseq_109_hg38.ser
INFO Deserialization took 12.92 sec.
Loading FASTA index...
Opening output VCF file...
WARN Invalid reference nucleotides in X:g.70504241G>A, should be A, auto-correcting.
```

**Expected behavior**
If the HGVS entry is invalid (reference or alt base with respect to transcript is incorrect), the variant should not be converted. An error should be logged in the VCF file for that variant.

**Additional context**

**Comment by holtgrewe** [comment]
Thanks for the report.

The code autocorrects to `A>A` which then causesa  loop when left-shifting.

The output will be

```
1       1       .       N       <ERROR> .       PARSE_ERROR     ERROR_MESSAGE=Problem+with+auto-correction;ORIG_VAR=NM_021120.3%3Ac.*1975G%3EA
```
