### ISSUE TITLE
Insertions are not annotated for splicing

### ISSUE THREAD

**Issue by dmb107** [charite/jannovar#554]
**Describe the bug**
I am not sure if this is a bug or intentional design, but I am noticing that insertion variants are not annotated for splicing information. I do not see the relevant splicing annotation logic in the `InsertionAnnotationBuilder` that I see in the `DeletionAnnotationBuilder`: https://github.com/charite/jannovar/blob/016e9fca19667c82d63632826673ae798a7ec265/jannovar-core/src/main/java/de/charite/compbio/jannovar/annotation/builders/DeletionAnnotationBuilder.java#L206-L214

Is Jannovar intentionally not considering splicing for insertions?

**To Reproduce**
Here is a left-aligned insertion that I expect to receive `splice_region_variant` based on the genomic position.
![Screen Shot 2022-07-12 at 2 30 11 PM](https://user-images.githubusercontent.com/8741841/178568145-3a501619-2ae8-4f25-b08f-82a143c1877a.png)

`annotate-var/refseq/hg19/chrX/108924495/C/CTTA`

```
[
	{
		"transcriptId": "NM_001318509.2",
		"variantEffects": [
			"disruptive_inframe_insertion"
		],
		"isCoding": true,
		"hgvsProtein": "p.(L212_K213insN)",
		"hgvsNucleotides": "c.636_638dup"
	},
	{
		"transcriptId": "NM_001318510.2",
		"variantEffects": [
			"disruptive_inframe_insertion"
		],
		"isCoding": true,
		"hgvsProtein": "p.(L171_K172insN)",
		"hgvsNucleotides": "c.513_515dup"
	},
	{
		"transcriptId": "NM_004458.3",
		"variantEffects": [
			"disruptive_inframe_insertion"
		],
		"isCoding": true,
		"hgvsProtein": "p.(L171_K172insN)",
		"hgvsNucleotides": "c.513_515dup"
	},
	{
		"transcriptId": "NM_022977.3",
		"variantEffects": [
			"disruptive_inframe_insertion"
		],
		"isCoding": true,
		"hgvsProtein": "p.(L212_K213insN)",
		"hgvsNucleotides": "c.636_638dup"
	}
]
```

**Additional context**
I ran VEP online to compare and found that the insertion is annotated with `splice_region_variant`.
![Screen Shot 2022-07-12 at 2 31 05 PM](https://user-images.githubusercontent.com/8741841/178568315-b31fdd7e-be17-4a25-9a5b-0a1211576cd8.png)

**Comment by dmb107** [comment]
Example variant with region `chr1:23685940-23696357`

SNV with splice_region_variant (positive control)
```
{
	"assembly": "GRCh37",
	"ref": "G",
	"alt": "T",
	"contig": "chr1",
	"start": 23382529,
	"stop": 23382529,
	"variant_type": "snv",
	"annotators": ["Jannovar"]
}

"data": {
			"transcriptId": "NM_001009999.3",
			"source": "refseq",
			"variantEffects": [
				"splice_region_variant",
				"synonymous_variant"
			],
			"isCoding": true,
			"hgvsProtein": "p.(=)",
			"hgvsNucleotides": "c.988A>C"
		},
```

Insertion within splice_region_variant boundaries without annotation:
```
{
	"assembly": "GRCh37",
	"ref": "A",
	"alt": "AC",
	"contig": "chr1",
	"start": 23382529,
	"stop": 23382530,
	"variant_type": "ins",
	"annotators": ["Jannovar"]
}

		"data": {
			"transcriptId": "NM_001009999.3",
			"source": "refseq",
			"variantEffects": [
				"frameshift_variant"
			],
			"isCoding": true,
			"hgvsProtein": "p.(R330Tfs*19)",
			"hgvsNucleotides": "c.988_989insC"
		},
```

**Comment by holtgrewe** [comment]
Good catch, thank you.
