### ISSUE TITLE
jannovar is prepending INFO with ;

### ISSUE THREAD

**Issue by leipzig** [charite/jannovar#88]
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	949696	CI128669	C	CG	.	.	;CLASS=DM;DNA=NM_005101.3:c.339dupG;EFFECT=STOPLOSS;GENE=ISG15;HGVS=ISG15:NM_005101.3:exon2:c.339dup:p.Leu114Alafs*?;MUT=ALT;STRAND=+
```
this is causing parsing problems in VariantAnnotation, probably some other programs

**Comment by holtgrewe** [comment]
Hm, I cannot reproduce this with the `v0.11` version. If I pass in your file then it even removes the leading semicolon. Could you try to pass the following file to Jannovar and see what happens? Could you give me the verbatim input file to Jannovar `v0.11` (it will complain about a missing VCF version in your file):

```
##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	949696	CI128669	C	CG	.	.	;CLASS=DM;DNA=NM_005101.3:c.339dupG;EFFECT=STOPLOSS;GENE=ISG15;HGVS=ISG15:NM_005101.3:exon2:c.339dup:p.Leu114Alafs*?;MUT=ALT;STRAND=+
```

**Comment by leipzig** [comment]
it is caused by semicolons at the end
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	949696	CI128669	C	CG	.	.	CLASS=DM;MUT=ALT;GENE=ISG15;STRAND=+;DNA=NM_005101.3:c.339dupG;
1	949739	CM128668	G	T	.	.	CLASS=DM;MUT=ALT;GENE=ISG15;STRAND=+;DNA=NM_005101.3:c.379G>T;PROT=NP_005092.1:p.E127*;
```

**Comment by holtgrewe** [comment]
Thank you for providing this additional information. Apparently, the HTSJDK interpretation (that we use for VCF I/O) interprets the standard such that this is an empty `INFO` field without a key or value. I will add an option to Jannovar that removes empty `INFO` (and `FILTER`) fields tomorrow and add this to the upcoming `v0.12`.
