### ISSUE TITLE
Implement more pedigree compatibility checks

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#95]
still missing:

- [x] X-linked, small
- [x] X-linked, large
- [x] AR, large
- [x] AD, large

**Comment by visze** [comment]
Hi Manuel,

ich kann den test, den wir am freitag geschreiben haben nicht fidnen. Habe bei deinem user im feature-brach feature/pedigree-checks geschaut..

**Comment by visze** [comment]
hab! feature/ped-tests

**Comment by holtgrewe** [comment]
The documentation has to clearly state the checks that are performed.

Also, we have to make clear that the aim of the filter is not to catch all pathological cases but only the "standard"/common ones. For example in the case of "unaffected father:ref, unaffected mother:het, affected son:hom", we do not consider the set of mutations to be compatible with autosomal recessive mode of inheritance.

**Comment by visze** [comment]
X-Recessive:

* We consider an hemizygous mutations in affected males as disease causing.
* We consider an heterozygous call in an affected male as disease causing => maybe estimated wrong from the caller
* [Singe case] We consider homozygous or two heterozygous mutations in an affected female as disease causing
* [Multiple case] We consider only homozygous mutations in affected females as disease causing. Compound het. will not be checked. Apparently the pedigree will look dominant.

Now the question: How should we handle het. unaffected males, when we have an affected female:

1. loose: Het. mutations in unaffected males are considered as FP calls and are NOT a disqualifying criterion
2.  strict:  A het. mutation in unaffected males IS a disqualifying criterion
3. strict/loose: Het. mutations in unaffected males are considered as FP EXCEPT the father of an affected female is heterozygous. (this is the actual implementation. not really consequent).

**Comment by pnrobinson** [comment]
Answers inline
________________________________________
Von: Max [notifications@github.com]
Gesendet: Mittwoch, 1. April 2015 12:05
An: charite/jannovar
Betreff: Re: [jannovar] Implement more pedigree compatibility checks (#95)

X-Recessive:

  *   We consider an hemizygous mutations in affected males as disease causing.
  *   We consider an heterozygous call in an affected male as disease causing => maybe estimated wrong from the caller
  *   [Singe case] We consider homozygous or two heterozygous mutations in an affected female as disease causing
  *   [Multiple case] We consider only homozygous mutations in affected females as disease causing. Compound het. will not be checked. Apparently the pedigree will look dominant.
==>> Dont understand why only homozygous?

Now the question: How should we handle het. unaffected males, when we have an affected female:

  1.  loose: Het. mutations in unaffected males are considered as FP calls and are NOT a disqualifying criterion
  2.  strict: A het. mutation in unaffected males IS a disqualifying criterion
=> I think #2 is preferable
  3.  strict/loose: Het. mutations in unaffected males are considered as FP EXCEPT the father of an affected female is heterozygous. (this is the actual implementation. not really consequent).

�

**Comment by visze** [comment]
@pnrobinson It can be compound heteozygous. but because of the X-Chromosome the father must be affected and homozygous. So the pedigree looks more dominant than recessive.

One mut. can be a de-novo mutation. But this is also covered by the XD case. This is similar to AR: Comp. het. will not be found, if one variant is de-novo. But the variant will show up in the AD filter.

**Comment by visze** [comment]
Ah Manuel and I designed a stupid test case for XR with a affected female:
![small_xr_stupid_female](https://cloud.githubusercontent.com/assets/9267120/6960626/9640917c-d924-11e4-9ae5-3be412d32043.png)

This case can only be true, if we have a de-novo variant at the same of carrier mutation of the mother. It is very unlikely, but I remember I had the case once, where the child has a het exon/gene deletion in the same gene...

This should be the more likely pedigree:

![small_xr_female](https://cloud.githubusercontent.com/assets/9267120/6960741/7623c714-d925-11e4-978e-9d63cf57d560.png)

**Comment by holtgrewe** [comment]
Is this done?
